### ISSUE TITLE
Support for different fonts/sizes

### ISSUE THREAD

**Issue by ChrisP4** [psifidotos/applet-window-appmenu#1]
Have a menu to choose text size as well as different installed fonts, like the active window control widget.

Thanks for all you're doing. Haven't tried it yet but I'm excited about the minimize aware stuff.

Επίσης στην περιγραφή που έχεις "based totally" πιο πολύ θα μου ταίριαζε αντί του totally, completely/fully. Βέβαια μπορεί να λέω και τελείως βλακείες.

**Comment by psifidotos** [comment]
> Have a menu to choose text size as well as different installed fonts, like the active window control widget.

sorry I dont like the idea

**Comment by ChrisP4** [comment]
Do you know how I can change the fonts of this widget (or generally any widget) because this widget (as well as the official global menu one) doesn't follow my universal font settings.

Thanks

**Comment by psifidotos** [comment]
you must change the qml code... So you must learn QML

**Comment by ChrisP4** [comment]
So there isn't an easy way to change this? A quick hacky sort of way?

If say I knew QML would it be easy to point to a specific font or is it a difficult problem?

**Comment by psifidotos** [comment]
I suppose you must find QML learning material...
