### ISSUE TITLE
Automatically add an empty cell/icon to appmenu categories that don't have any

### ISSUE THREAD

**Issue by Jonchun** [psifidotos/applet-window-appmenu#101]
Depending on whether there exists a little icon/cell such as the checkbox for "Work Offline" in the Firefox File menu, or the little favicons in the history tab, compared to the "Edit" Menu that has no icons/checkboxes, the spacing is inconsistent between menus. Personally I think it looks better if it just always has that one "tab" worth of space, and I think that it should be an option.

![image](https://user-images.githubusercontent.com/5800539/78466775-9ba9e080-76d3-11ea-82ec-491e6e164d72.png)

Edit: Maybe this is really a bug? Unsure.

**Comment by psifidotos** [comment]
This Qt default behavior for menus.
