### ISSUE TITLE
Document dependencies for REHL installs

### ISSUE THREAD

**Issue by chase9** [psifidotos/applet-window-appmenu#102]
To make it easier for users to get started, the proper dependencies for Fedora/RHEL should be included in the install markdown file.

I'm sure the package `libSM-devel` is required but not sure about what others are. After collecting all of the necessary packages, we can update INSTALLATION.md.

**Comment by psifidotos** [comment]
No problem, in all my projects INSTALLATION. md files are totally community driven. Just make a PR and I will accept it

**Comment by chase9** [comment]
I added what I believe to be the required dependencies. I did this by just translating the package names from APT to RPM, but can't personally test it since many things will be uninstalled on my system :sweat_smile:
