### ISSUE TITLE
Only have menu appear on mouse over

### ISSUE THREAD

**Issue by sianhulo** [psifidotos/applet-window-appmenu#104]
I'm trying to use this as a replacement for https://store.kde.org/p/998910/ . But this requires more horizontal space as the title and menu would both appear at the same time,I'd like the option to have the menu only appear on mouse over so it only takes space when I'm going to use it.

**Comment by psifidotos** [comment]
this option is only available when you use the AppMenu in Latte in conjuction with Window Title. You can show the AppMenu only when the mouse hovers the Window Title applet

**Comment by sianhulo** [comment]
I installed latte-dock and it is as you say. However, the behavior is different from what I'm used to, is there any chance you could add the option so that hovering the mouse over any area from the applet triggers the menu? right now it's only triggered if the mouse is over the title itself so we have to first move to the title and then to the button rather than going to where we expect the button to be directly (only the case if the button is more to the right than title's "boundary")

**Comment by psifidotos** [comment]
nope this is not possible.
Only thing you can do is to set **both** Window Title and Window AppMenu to Fill All available free space in order to increase the area that needs to be hovered.

**Comment by sianhulo** [comment]
maybe I'm misunderstanding something but menu only appears if you are hovering on title, so I don't see how changing appmenu would affect this behavior, regardless, I tried and didn't notice any difference. I can't set window title to use all available space because then it shrinks the panel to try and accommodate for titles are too long to fit in available space.

Just to clarify, I don't care if I can't trigger menu by hovering at any point on the panel, I just want to be able to hover on the space that's already being reserved by window title (in my case 906px) and have the menu appear, which doesn't happen if the space is reserved but not currently occupied by the title.

**Comment by psifidotos** [comment]
Send your Latte layout file to tell you what you need to configure differently

**Comment by sianhulo** [comment]
Here it is
[unity-2.layout.latte.zip](https://github.com/psifidotos/applet-window-appmenu/files/4477270/unity-2.layout.latte.zip)

**Comment by psifidotos** [comment]
works just as fine as long as you enable:
Window Title settings -> Length -> Fill available space

**Comment by sianhulo** [comment]
the problem with that is that it makes the panel shrink if the title of the focused window is too long.... or was a few minutes ago, it isn't shrinking now for some reason, I'll have to test further.

**Comment by psifidotos** [comment]
1. Enable the option
2. Restart Latte and you probably won't have any problem

**Comment by sianhulo** [comment]
well, it seems to be working well, thank you.
