### ISSUE TITLE
[feature request] show only for maximized windows

### ISSUE THREAD

**Issue by gobonja** [psifidotos/applet-window-appmenu#105]
Would it be possible to implement option to show appmenu only for maximized windows?

I am using material-decoration with latte dock borderless option so if window is not maximized I get 2 menus.
![normal](https://user-images.githubusercontent.com/26535797/79808073-fa768780-836c-11ea-96d5-3328ae43dc2d.png)
![maximized](https://user-images.githubusercontent.com/26535797/79808076-fe0a0e80-836c-11ea-8765-07752d9d8248.png)

Thanks in advance

**Comment by trmdi** [comment]
A video about the behavior of Unity: https://youtu.be/nzFXRz-b3Ns?t=40

**Comment by psifidotos** [comment]
Ok the video explains it, really nice, that way it has meaning

**Comment by psifidotos** [comment]
but of course this is not the easiest thing to provide. Especially if this behavior is combined with Window Title unity mode case
