### ISSUE TITLE
Firefox 75 no longer has menu in Latte bar in Kubuntu 20.04

### ISSUE THREAD

**Issue by stderr-to-devnull** [psifidotos/applet-window-appmenu#108]
Firefox had menu in Latte bar in 19.04 and 19.10. After upgrade to Kubuntu 20.04, menu bar no longer appears. Re-installed applet successfully (0.6.0) and rebooted. Menu for all the other apps works so the issue is isolated to Firefox.

**Comment by trmdi** [comment]
Still working fine on openSUSE.

![Screenshot_20200504_204838](https://user-images.githubusercontent.com/11857205/80972723-a5e10b00-8e48-11ea-9726-1bb35953a16a.png)

**Comment by AliTajelsir** [comment]
In arch to have Firefox menu work with a menu bar, I needed `libdbusmenu-gtk3` installed and also a patched Firefox `firefox-appmenu-bin`.

**Comment by psifidotos** [comment]
you have to contact your distro to fix or give you instructions how to fix this... 

this is not appmenu applet responsibility.
