### ISSUE TITLE
[Question] How the global menu works ?

### ISSUE THREAD

**Issue by SeptemberHX** [psifidotos/applet-window-appmenu#110]
Hello, I am very confused about the principle behind the global menu. I tried to figure it out by reading the source code, but no lucky. Could you please show me how it works ?

I am trying to figure out whether it is possible to implement the same global menu on other desktop environment: DDE(deepin desktop environment) of Deepin V20, and DDE doesn't use most of the plasma components except the kwin.

However, I noticed that there is also another extension for GNOME which also enables the global menu. So I think there may be a way to implement the global menu  which is platform independent.

Thus, my question is as follows:

1. Is it possible to implement the global menu on other DE than KDE and GNOME ?
2. How the global menu works ? It seems the dbusmenu-qt is essential, but I can't find any document or tutorials about it.

Thanks !

**Comment by psifidotos** [comment]
there is a service for application appmenus. In plasma this is provided from plasma-workspace. Sorry but this is not my expertise I just used the plasma applet appmenu in order to build on top of it for plasma workspace and as such to create the window appmenu applet
