### ISSUE TITLE
Make a connection between the config of this and applet-window-title

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-appmenu#111]
I'm talking about the two options of these applets:
![image](https://user-images.githubusercontent.com/11857205/82171346-3e6b9680-98f1-11ea-9e55-4f3f2905e595.png)
![image](https://user-images.githubusercontent.com/11857205/82171374-53482a00-98f1-11ea-94fd-0a48eedf6f78.png)

They only work if both are chosen. So when the user changes one, the other should also change automatically.

**Comment by psifidotos** [comment]
Makes sense, I believe it can be provided easily for both.

**Comment by psifidotos** [comment]
Now that I think it again the fix must be really careful. Only activating the option must inform all other applets that they should follow the new option. In the chance that a user has two or more Window Titles in the same panel he must be able to disable that option in an of them without disabling it for all the rest

**Comment by trmdi** [comment]
Sorry, I've just tested it but it didn't work. When I uncomment this line: https://github.com/psifidotos/applet-window-title/blob/b08d5f9a8e9a2938bb0fec24ff12c299181a2a16/contents/ui/Broadcaster.qml#L78
And change the option from applet-window-appmenu, I don't see that log.

**Comment by psifidotos** [comment]
have you updated both appmenu and window title ?

**Comment by psifidotos** [comment]
work just fine on my side.

**Comment by trmdi** [comment]
Yes:
> applet-window-appmenu: f5b1635
> applet-window-title: b08d5f9
> latte-dock: 78dce5d5

Btw, I see this error:
> [Warning : 23:27:32.577577] - "file:///usr/share/plasma/plasmoids/org.kde.windowappmenu/contents/ui/main.qml: ReferenceError: lastActiveWindow is not defined"

**Comment by psifidotos** [comment]
warnings should be fixed now, for the issue not working for you, I have no idea.

**Comment by trmdi** [comment]
I remember you posted an article about Latte bridge but I can't find the link. Could you give me the link in order to debug it. It seems that somehow appmenu can't send the message to applet title through Latte bridge.

**Comment by psifidotos** [comment]
https://techbase.kde.org/LatteDock

**Comment by psifidotos** [comment]
Latte bridge implementation is found at https://invent.kde.org/plasma/latte-dock/-/tree/master/containment/package/contents/ui/applet/communicator

**Comment by trmdi** [comment]
latteBridge.actions.broadcastToApplet("org.kde.windowtitle", "activateWindowTitleCooperationFromEditMode", true);

Why only set this when the user enables it? I think it should also broadcast the "disable" message. When the user disables one, the other should also be disabled automatically.

**Comment by psifidotos** [comment]
In that case all window title applets will be disabled and so the user can not have one connected and one that is never connected

**Comment by trmdi** [comment]
Yes, the multiple applets case is difficult. Can latte know about the neighbor of an applet?

**Comment by psifidotos** [comment]
> Yes, the multiple applets case is difficult. Can latte know about the neighbor of an applet?

It can now the neighbor of applets but this is not exposed to applets

**Comment by trmdi** [comment]
> > Yes, the multiple applets case is difficult. Can latte know about the neighbor of an applet?
> 
> It can now the neighbor of applets but this is not exposed to applets

I think if this is exposed the behavior should be much better, because users usually use this option for appmenu and apptitle that are neighbor of each other.

**Comment by psifidotos** [comment]
sorry, I don't agree, is starting to become too messy.
