### ISSUE TITLE
Menus not opening for some apps and weird alt+tab behavior

### ISSUE THREAD

**Issue by caph1993** [psifidotos/applet-window-appmenu#112]
In the screen recording below I show things working normally in Chrome, then the issue in the app LYX. Only one menu option (Tools) shows the dropdown menu. Then, I select the fifth option in LYX and I switch back to Chrome using alt+tab. Instead of the menu being cleared in Chrome, the fifth option appears highlighted, and in the screen recorder app the fifth option is highlighted as well.

![global-menu-bug](https://user-images.githubusercontent.com/5473460/82959223-d2d29a80-9f7c-11ea-99b5-01cefa54bf98.gif)

I have faced this issue several times when using the app LYX, but not always, and not only with LYX. Sometimes the menu stops working for all apps. Maybe it is related to the large size of the LYX menu.

Is there any log I can provide whenever it happens again?

**Comment by psifidotos** [comment]
Do you have the same issue with Plasma global menu?

**Comment by caph1993** [comment]
My mistake. I was using Plasma global menu instead of this applet.
I should report the issue to Plasma global menu instead.

**Comment by caph1993** [comment]
I am reopening the issue because I have just confirmed that it also happens with this applet.
Is this issue inherited from Plasma global menu or is this applet a different implementation?
If the latter, then maybe the issue has something to do with LYX or with using alt+letters to access and navigate the menu. I do that very often in LYX.
