### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by MaxVerevkin** [psifidotos/applet-window-appmenu#114]
This applet does not work in wayland session. Is it technically possible to have global menu in wayland? Is it Plsama issue? The first issue about wayland was opened almost 2 years ago, and nothing changed?

**Comment by fushinari** [comment]
It should be possible from 5.19 onwards, let's hope @psifidotos gets around to using the new APIs to redo this

**Comment by psifidotos** [comment]
I have just implemented it.. but the thing is that it needs Plasma Desktop >= 5.19 in order to be built... So now the question is do we drop support for all Plasma before 5.19 ?
Is there a way to disable that codepath during building?

@trmdi any ideas

**Comment by trmdi** [comment]
Probably Plasma 5.18 is still used by some distro like Leap, Kubuntu... Could we support both? For example, use cmake to detect the version of plasma, then use c++ preprocessors... I don't know.

**Comment by psifidotos** [comment]
Problem is that I think cmake does not have a cmake way to detect plasma version. I have a cmake way to detect kde frameworks version but I don't think it is enough. Plasma 5.18 may use same kf5 version with Plasma 5.19

**Comment by trmdi** [comment]
Then can we have a cmake option for it?

**Comment by psifidotos** [comment]
If I don't find another I think the best is to use current implementation at all cases and if the user has added a flag e.g.   install.sh --enable-wayland

It will build also the wayland parts

**Comment by trmdi** [comment]
>  install.sh

I think a cmake option would be easier for packagers. They usually use cmake instead of install.sh.

**Comment by psifidotos** [comment]
> > install.sh
> 
> I think a cmake option would be easier for packagers. They usually use cmake instead of install.sh.

Found it.... Plasma LibTaskManager exposes as its version to be equivalent with the Plasma Desktop from which is based. CMake now identifies this e.g. LibTaskManager 5.19.4 

afterwards if optional LibTaskManager is found it enables the wayland paths only if LibTaskManager>=5.19.0

**Comment by psifidotos** [comment]
so no flags are needed, it works automagically.... if someone wants wayland support should install plasma-workspace-dev and rebuild, that is all

**Comment by psifidotos** [comment]
feel free to report your findings...
In my system everything related to AppMenu and mouse interaction works just fine, entering/exiting/hovering/unity mode etc...

keyboard navigation it does not  and I dont really know yet how this should be approached in wayland...

**Comment by trmdi** [comment]
Oops... Build failed on Leap: https://build.opensuse.org/package/live_build_log/home:trmdi/applet-window-appmenu/openSUSE_Leap_15.2/x86_64

**Comment by psifidotos** [comment]
1. It needs Plasma Desktop>=5.19 , does it offer that?
2. And of course KF5::Wayland>=5.69, does it offer that?

but I believe I think it should build but not working at all in Leap....

**Comment by psifidotos** [comment]
@trmdi ok... you can try again... it should build now for plasma desktop<=5.18 but of course under wayland wont show anything

**Comment by trmdi** [comment]
Succeeded. Thanks. <3

**Comment by psifidotos** [comment]
> Succeeded. Thanks. <3

no worries. Did you try it under wayland?

**Comment by trmdi** [comment]
> > Succeeded. Thanks. <3
> 
> no worries. Did you try it under wayland?

Not yet. I've just built it on OBS. I still use X and feel wayland is not stable enough to use currently. 😁
