### ISSUE TITLE
[Feature request] Drag to restore from this widget

### ISSUE THREAD

**Issue by rodrigopedra** [psifidotos/applet-window-appmenu#118]
[ Moved from https://github.com/psifidotos/applet-window-title/issues/100 ]

Is it possible that the behavior from Latte Dock to restore a window size when dragging from the panel be added to this widget?

If that would be possible one could use this widget in a regular plasma panel while still keeping that very useful behavior. I don't know if that is possible, or feasible, but I was wondering when the expand to max-width option is checked if that behavior could be added directly to this widget.

Right now I only use Latte on my top panel due to that behavior, but I still have a regular empty plasma panel behind it as desktop icons get under latte dock.

I believe I saw this tip to workaround icons getting behind the panel from one comment from @psifidotos on some other issue.

I still use Latte dock on the bottom for my application icons and not intend to stop using it.

**Comment by psifidotos** [comment]
Sorry not possible

**Comment by rodrigopedra** [comment]
Ok, thanks for the quick response and thanks for the widget.
