### ISSUE TITLE
Request: Option for visual divider or distinction between top level items

### ISSUE THREAD

**Issue by AndydeCleyre** [psifidotos/applet-window-appmenu#120]
My use case is that I want to keep the applet compact, but still clearly see where one menu button ends and the next begins.

![image](https://user-images.githubusercontent.com/1787385/84805658-9bcb3400-afd2-11ea-8fb9-ead4a739c502.png)

This would be especially useful for cases where a menu item is more than one word:

![image](https://user-images.githubusercontent.com/1787385/84806407-9fab8600-afd3-11ea-810b-15740934f785.png)

Some possible solutions:

1. a faint `|`-like icon/character between each -- ideally not adding any width
2. alternating background colors
3. alternating foreground colors
4. alternating font style (bold/italic)
5. some "indicator" style mark for each item

What do you think, is there a good way to keep it compact and also easily differentiate one from the next?

**Comment by psifidotos** [comment]
you can increase the items spacing in order to achieve this

**Comment by AndydeCleyre** [comment]
This request was for a way

> to keep the applet compact, but still clearly see where one menu button ends and the next begins

Increasing the spacing does not achieve this, it dismisses half of the goal.

**Comment by psifidotos** [comment]
it is the only visible solutions, feel free to provide mockups and arguments for any different solution that you find appropriate

**Comment by AndydeCleyre** [comment]
Here's a quick mockup of suggested solution number 1. I used the color scheme's Inactive Text color, at 50% opacity.

![latte_mockup](https://user-images.githubusercontent.com/1787385/84810807-da182180-afd9-11ea-8993-a90e468cafac.png)

And here it is with 20% opacity, which is probably better:

![latte_mockup2](https://user-images.githubusercontent.com/1787385/84811035-409d3f80-afda-11ea-84e4-44770fa6bfb0.png)

What kind of argument are you looking for; why isn't enough to say that both compact and unambiguous representation may be desired?

**Comment by psifidotos** [comment]
I could consider only something that looks nice and improves the situation...
From my perspective spacing is still the only winner.
