### ISSUE TITLE
Alt triggers menus

### ISSUE THREAD

**Issue by huyndnse63331** [psifidotos/applet-window-appmenu#121]
When you hold Alt, those texts will be underline which is waitng for another key is pressed and trigger the specific menu, like Alt + F will trigger File menu. I wonder if there is any way i can press Alt + Shift + F without triggering the menu bar while the menu bar shows everything like this.

![image](https://user-images.githubusercontent.com/25204246/85942013-cdd48280-b950-11ea-8b57-09de311f347d.png)

How can i change this behavior?

**Comment by psifidotos** [comment]
Probably disabling the behavior or choosing a different modifier could be a solution

**Comment by huyndnse63331** [comment]
> Probably disabling the behavior or choosing a different modifier could be a solution

By disabling the behavior, you mean?

**Comment by psifidotos** [comment]
I mean that in a best case scenario if the user will choose None modifier to trigger application menu then the menus will never be triggered and will never look underlined

**Comment by huyndnse63331** [comment]
I'm not setting any key to trigger this, this is like the default behavior 😢 

![image](https://user-images.githubusercontent.com/25204246/85942727-4dfce700-b955-11ea-943c-2330743fad25.png)

**Comment by psifidotos** [comment]
do you know how to develop in qt/qml?

**Comment by huyndnse63331** [comment]
Unfortunately, no 😭

**Comment by psifidotos** [comment]
sorry someone must provide a PR for this... a new option in order for the user to specify the modifier and if None is chosen then the modifier will not work at all.
