### ISSUE TITLE
[feature] Show menu on hover

### ISSUE THREAD

**Issue by divinae** [psifidotos/applet-window-appmenu#123]
What do you think about new option:
single button -> focus/hover on (like Window Title + Appmenu) -> full menu visible

**Comment by psifidotos** [comment]
no idea, screenshots and detail explanation

**Comment by divinae** [comment]
![Screenshot_20200701_124633](https://user-images.githubusercontent.com/49128105/86235971-91479780-bb99-11ea-8398-cdd287ff8eaf.png)
![Screenshot_20200701_124550](https://user-images.githubusercontent.com/49128105/86235974-9278c480-bb99-11ea-87c6-fd4cd14b3e23.png)

**Comment by psifidotos** [comment]
already provided with Latte panels + Window Title + Window AppMenu applets

**Comment by divinae** [comment]
Not exacly. With Window Title + AppMenu I could not have static "menu" icon.

**Comment by psifidotos** [comment]
What is a static menu icon?

**Comment by psifidotos** [comment]
Why don't you just show the current window icon and when hovering it to show the window appmenu?

**Comment by divinae** [comment]
It looks bad with my setup
![Screenshot_20200702_155206](https://user-images.githubusercontent.com/49128105/86367329-16a37880-bc7c-11ea-9ddf-fd1b6b9fa490.png)

**Comment by psifidotos** [comment]
So you want a hovering icon to expand appmenu. Sorry I think I am not interested.

**Comment by divinae** [comment]
It's ok :)
In free time I will try to implement it myself
