### ISSUE TITLE
Shortcut doesn't open menu

### ISSUE THREAD

**Issue by jereksel** [psifidotos/applet-window-appmenu#124]
Hi

I've set shortcut in your plasmoid, but invoking it does not do anything. Original plasmoid opens first menu.

I've tested it on lattedock 0.9.11

**Comment by Dhamma-valence** [comment]
Same problem for me too, though for me it doesn't show anything, no text, not even a button when I change to the single button mode. The only time I see anything at all from it is when I'm in the latte-dock editing mode.

**Comment by psifidotos** [comment]
should be fixed now... test latest Latte and latest applet version
