### ISSUE TITLE
doesn't show the full menu while using vertical latte dock 

### ISSUE THREAD

**Issue by shiran1909** [psifidotos/applet-window-appmenu#125]
when  set latte dock to left, the full menu doesn't show,it is only show a list icon.

![1](https://user-images.githubusercontent.com/10594067/87960365-caaf5b00-cae6-11ea-8965-13ad8fd2a2aa.png)
![2](https://user-images.githubusercontent.com/10594067/87960630-2974d480-cae7-11ea-805c-dedf5d9fa493.png)

**Comment by psifidotos** [comment]
This is intentional, for the same reasons that pkasma global menu is also doing.

**Comment by finkrer** [comment]
![image](https://user-images.githubusercontent.com/22712590/109783670-0dfcab00-7c2c-11eb-9de5-0ff93cb39194.png)
But it doesn't? I see nothing wrong with this use case. Supporting it would be nice since the default global menu doesn't support Latte's theming.
