### ISSUE TITLE
[Wayland] Open menus won't close properly

### ISSUE THREAD

**Issue by fushinari** [psifidotos/applet-window-appmenu#126]
If a menu is opened and then you click on the same menu, you expect it to close. But right now in Wayland, it does not close that way. It also does not close if you click anywhere else on the panel.

upstream Qt bug: https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-83972

**Comment by psifidotos** [comment]
wayland, wayland... popups and menus broken all over the place...

**Comment by fushinari** [comment]
Yep, lol. Also, did I mention how GTK3 apps' menus are broken on Wayland?

**Comment by psifidotos** [comment]
Of course they are... Gnome has not made any technology yet to support them. If Gnome provides a solution in the future, plasma devs have said they will try to support it.

**Comment by psifidotos** [comment]
XWayland applications do not work?

And why libreoffice, Inkscape and gimp work just fine in my system?

**Comment by fushinari** [comment]
> XWayland applications do not work?
> 
> And why libreoffice, Inkscape and gimp work just fine in my system?

XWayland does work, sorry for that.

Are you sure you're on Wayland? Inkscape is GTK3... It should be impossible to work with. Or is it running over XWayland?

**Comment by psifidotos** [comment]
https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-83972

**Comment by psifidotos** [comment]
Probably Inkscape in my system enforces xcb use... It can do so from its desktop file if you want to also try it.

**Comment by fushinari** [comment]
Not your bug then. :)

Yes, I'd like to try it.

**Comment by psifidotos** [comment]
my inskape desktop file has a record:
`Exec=env GTK2_RC_FILES=/usr/share/themes/Breeze-Dark/gtk-2.0/gtkrc inkscape %F`

I suppose for the rest apps will be also another way to enforce XWayland for them in order to work properly.

**Comment by fushinari** [comment]
I used GDK_BACKEND=X11 to test this. You were right. It works fine with GTK3 apps running over XWayland.

**Comment by fushinari** [comment]
Should I be closing this or should I be leaving it open? I mean, it's not your bug and will probably get fixed upstream at some point...

**Comment by psifidotos** [comment]
Leave it open and I will tag it upstream.

**Comment by michaldybczak** [comment]
Situation seems to be better on now. There are some menu issues, but at least on my system, I was able to open and close them properly - Plasma 5.24, Wayland.
Looks like this issue is now fixed upstream, but I can be mistaken. Can someone check how it works now, providing you already have the newest Plasma?

**Comment by psifidotos** [comment]
somehow Plasma fixed this, but unfortunately I can not figure out how Plasma 5.24 worked around this.... Relevant Latte bug tracker is: https://bugs.kde.org/show_bug.cgi?id=454886

**Comment by zany130** [comment]
was about to open a new issue but I think it's the same as this if I open a menu and then go to open a different one it won't open.  It will highlight the menus as if they were being opened but nothing shows
![image](https://user-images.githubusercontent.com/25832539/174161337-a20d4c06-491f-43cf-a826-64a1904a7888.png)

**Comment by psifidotos** [comment]
use git version

**Comment by zany130** [comment]
yup building and installing the latest applet from here works fine didn't have to switch to latte -git

**Comment by csolisr** [comment]
BRB, checking out the Git branch - thank you so much, it was my last blocker to stay on Wayland
