### ISSUE TITLE
[Feature request] Hide menu and show on mouse hover or Alt key

### ISSUE THREAD

**Issue by petsam** [psifidotos/applet-window-appmenu#13]
As the title says.
Because with Window Title applet text being long and at the same time having a long menu, it would  be a nice solution to have the option of a hidden menu, until it (the empty space, or the Window Title text) is hovered, or press Alt key for activation.
This could (if possible) "make" Window Title to hide, until the menu is hidden again.

**Comment by psifidotos** [comment]
I don't like the idea. The goal is that all three Window applets  to be able to behave the same

**Comment by petsam** [comment]
> I don't like the idea.

The idea was for each component to show up when needed, with possibility of the user to apply a preference, just like the buttons that hide on un-maxinized, with user choice.
Better follow your instinct, though.
Thanks for listening. :+1:  :)

**Comment by trmdi** [comment]
@petsam
You can use `Title Substitution` to elide a long title.
E.g. Firefox Web Browser -> Firefox
