### ISSUE TITLE
[feature request] "last active window is maximized" configuration option.

### ISSUE THREAD

**Issue by cyclinggeorgian** [psifidotos/applet-window-appmenu#130]
If i may, I would like to request a very same settings option that applet-window-buttons applet has -  last active window is maximized.
I understand that initial desire for global menus - when screens were small top panel was used to save that space...on the modern "gigantic" monitors having menu in far left corner from window itself feels unnatural. Unless window is maximized... maximizing window == urge to use screen estate to it's max. Then global menu makes sense again..as well as hiding window borders that latte oh so conveniently provides (thanks for that by the way).

**Comment by psifidotos** [comment]
Isn't that already implemented? Have you try appmenu master version with Latte?

**Comment by cyclinggeorgian** [comment]
yes you are right... in the master branch config option is present.
thank you
