### ISSUE TITLE
Vivaldi menu

### ISSUE THREAD

**Issue by Sadi58** [psifidotos/applet-window-appmenu#131]
I don't know if this is a bug report or feature request or even nothing other than trying to find a special fix/workaround to address an issue arising from the  app concerned.
It seems the increasingly popular web browser Vivaldi has a peculiar way of displaying menu - something in between Chromium and Firefox - that makes it impossible to display it via applet-window-appmenu like other apps. Pressing Ctrl+M only results in displaying the app menu on an app-specific title bar.
I wonder if something can be done about this...

**Comment by psifidotos** [comment]
It is Vivaldi responsibility to support appmenus, nothing to do with this applet. Is it showing properly with Plasma global menu applet? If it isn't, it problem means that Vivaldi does not support the functionality.
