### ISSUE TITLE
Only top level menu available

### ISSUE THREAD

**Issue by pantale** [psifidotos/applet-window-appmenu#132]
Hi,

I have installed the applet, but unable to use it since, only the top level of menus is available (File, Edit, History,...,Help) for example with chrome. If I click on any menu, nothing happens.

I'm on Neon Kde 5.19.4 20.04.

Olivier

**Comment by psifidotos** [comment]
1. Is that only with Chrome?
2. Use a plasma panel with Plasma Global menu applet, does it work correctly?

**Comment by pantale** [comment]
No, it happens with all applications.
Plasma Global menu applet works fine.

**Comment by psifidotos** [comment]
1. Xorg or wayland?
2. Are you using latest master version?

**Comment by pantale** [comment]
I'm using Xorg, with the latest master version.

**Comment by psifidotos** [comment]
works just fine in my system for all apps

**Comment by pantale** [comment]
Found the problem and solved it.

I related it to my anaconda installation, had to disable anaconda before compiling. Seems that the anaconda distribution contains some qt5 libraries that conflict with the one present in my system.

Sorry for that, I thought about it last night!

Olivier

**Comment by psifidotos** [comment]
No prob.
