### ISSUE TITLE
In "show only button" mode it crash whole plasmashell

### ISSUE THREAD

**Issue by Moriarty1** [psifidotos/applet-window-appmenu#134]
Arch linux
Step to reproduse
1. Install https://aur.archlinux.org/packages/plasma5-applets-window-appmenu-git/
2. Set settings to show only button
3. Slick on menu button to show menu and click again
[log.txt](https://github.com/psifidotos/applet-window-appmenu/files/5179319/log.txt)

**Comment by Moriarty1** [comment]
As a "nice to have" request:
Have possibility to change button size
![image](https://user-images.githubusercontent.com/3141470/92322560-e7b5d400-f029-11ea-9291-9ebb77090e87.png)

**Comment by psifidotos** [comment]
1. no crash report so I can not track back the code... I suppose you are using the applet inside a plasma panel no idea what is happening in that case... I use the applet only inside Latte panels
2. for the icon size feature, sorry I am not interested

**Comment by psifidotos** [comment]
just checked... no crash in my computer with plasma panels and single button... You probably need to build install the applet by yourself and no really on AUR for this.
