### ISSUE TITLE
Impossible to install on Manjaro (Arch)

### ISSUE THREAD

**Issue by chaletweb** [psifidotos/applet-window-appmenu#138]
hello, 
I can't install on my manjaro distrib. This system use Pacman. 
Could you please tell me what is the command line ?

**Comment by X-Ryl669** [comment]
You need to build it yourself. It's quite easy:
`git clone https://github.com/psifidotos/applet-window-appmenu.git && cd applet-window-appmenu && ./install.sh`

**Comment by chaletweb** [comment]
I've tried it but without result 

this error in output : 
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:15 (find_package):
  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/rico/Téléchargements/applet-window-appmenu/build/CMakeFiles/CMakeOutput.log".
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.

**Comment by chaletweb** [comment]
Yes it works after the installation of extra cmake module (5-75-0.1)
Thanks for all
