### ISSUE TITLE
Dont work with some app (eg: filezilla and gimp)

### ISSUE THREAD

**Issue by laltroweb** [psifidotos/applet-window-appmenu#139]
Manjaro testing. Ok with chrome and dolphin etc, issue with some other apps like filezilla or gimp (see screen).

![Screenshot_20201119_153054](https://user-images.githubusercontent.com/16841896/99679460-43fe9080-2a7c-11eb-8742-f97b8d583d70.png)

![Screenshot_20201119_153138](https://user-images.githubusercontent.com/16841896/99679536-54af0680-2a7c-11eb-9356-dadedfe4a731.png)

![Screenshot_20201119_153159](https://user-images.githubusercontent.com/16841896/99679568-60023200-2a7c-11eb-9fa4-a17d0b8d2ecf.png)

![Screenshot_20201119_153215](https://user-images.githubusercontent.com/16841896/99679603-6c868a80-2a7c-11eb-9b9f-cdcef2cbfe18.png)

Anyway, work best than Default Global menu :)

**Comment by trmdi** [comment]
They do work, but need some dependencies.
For Thunderbird, you need to install the patched version, search for "thunderbird-aoomenu"

**Comment by laltroweb** [comment]
I don't use thunderbird... Seen this, atm, just with filezilla and gimp. If is a dependency issue, i can try and verify. Ty 👍

**Comment by laltroweb** [comment]
thank'u again (seen now my mistake in title, real sorry!!!).
anyway, fixed thanks to **appmenu-gtk-module**

So, fixed :+1:
