### ISSUE TITLE
Kontact - length is faulty when menu is updated without changing applications

### ISSUE THREAD

**Issue by moffis** [psifidotos/applet-window-appmenu#14]
This seems to be a problem when not switching applications. 
See video attached (remove .zip)

[bug.webm.zip](https://github.com/psifidotos/applet-window-appmenu/files/2603763/bug.webm.zip)

**Comment by psifidotos** [comment]
this was related to Latte panels... you will need latest Latte git to work this properly,

Latte Dock >= 0..8.4

for plasma panels it works fantastic now...
