### ISSUE TITLE
No close button on Firefox when "Customize > Title Bar" option is disabled.

### ISSUE THREAD

**Issue by DenysMb** [psifidotos/applet-window-appmenu#140]
When I use Firefox, disable the Title Bar and use this widget, the close button goes away.
![image](https://user-images.githubusercontent.com/33737137/102663995-a5d81600-4160-11eb-8d14-c54bf753fccc.png)

There is no option like "Show/Hide window buttons"
![image](https://user-images.githubusercontent.com/33737137/102664154-f2235600-4160-11eb-9ff6-7f72937487e9.png)

So, what can we do?

**Comment by trmdi** [comment]
https://www.reddit.com/r/kde/comments/imnpny/firefox_global_menu_patch_removes_the_headerbar/

**Comment by DenysMb** [comment]
> https://www.reddit.com/r/kde/comments/imnpny/firefox_global_menu_patch_removes_the_headerbar/

@trmdi That worked. Thank you very much!
