### ISSUE TITLE
Can't compile on Debian Bullseye - Could NOT find XCB (missing: RANDR)

### ISSUE THREAD

**Issue by AntoninJcb** [psifidotos/applet-window-appmenu#141]
Hi,
I've installed every packages mentioned in INSTALLATION.md, but I get this error when trying to perform `sh install.sh`
```bash
install.sh: 1: [: -a: unexpected operator
mkdir: cannot create directory 'build': File exists
-- Could NOT find XCB_RANDR (missing: XCB_RANDR_LIBRARY XCB_RANDR_INCLUDE_DIR) (found version "")
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find XCB (missing: RANDR) (found version "1.14")
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindXCB.cmake:166 (find_package_handle_standard_args)
  plugin/CMakeLists.txt:32 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/antonin/Downloads/applet-window-appmenu-0.6.0/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

I'm running Debian Bullseye.
These are my system info:
```
Operating System: Debian GNU/Linux
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.9.0-5-amd64
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-7700HQ CPU @ 2.80GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630
```

Thanks for your help!

**Comment by trmdi** [comment]
That means you have to install some package for the missing thing.

**Comment by AntoninJcb** [comment]
Yes, thank you. But I can't find a clue about what package I am missing. I don't know where to look for, querying google for this XCB and RANDR thing leads me to very unrelated problems.
I might have missed something, I'm a beginner and not used to compile code yet.

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by trmdi** [comment]
You should ask debian guys for this distro-specific question. I suggest to go to /r/debian.

**Comment by AntoninJcb** [comment]
> You should ask debian guys for this distro-specific question. I suggest to go to /r/debian.
> Try `libxcb-randr0-dev`. (just a guess)

Hi again, thanks a lot for your suggestion.
Indeed, a quick `apt-get install libxcb-randr0-dev` did the trick! The installation processed worked like a charm after that.

I hope it will help other folks out there.
I'm closing the issue, have a nice day!
