### ISSUE TITLE
Option "Show only menus from active applications" not working.

### ISSUE THREAD

**Issue by tnilzon** [psifidotos/applet-window-appmenu#142]
In the applet options/General there is a filter: "Show only menus from active applications", but it is not working. What happens is:

If a window of an application that has menus is selected on the desktop (i.e. is "active") the menus are correctly displayed in the panel (on the "applet-window-appmenu"). If then an empty space on the desktop is clicked, this application becomes not selected (i.e. is not "active"), then the menus are still displayed in the panel. Expected behavior is that the menus should disappear.

**Comment by psifidotos** [comment]
Have you tried latest master version?

**Comment by tnilzon** [comment]
Hi, just tried the master. It works!
Thanks!
