### ISSUE TITLE
[Feature] Exception-List for Applications

### ISSUE THREAD

**Issue by FeWa-zu** [psifidotos/applet-window-appmenu#145]
There are certain applications that are buggy when using appmenu (it's the same if using the "offical" KDE global-menu) like Lyx.
So, an option to exclude certain applications from using appmenu would be a great help!

Thank you very much for the great applet!

**Comment by trmdi** [comment]
You can run the app with the KDE_NO_GLOBALMENU=1 environment variable.

**Comment by D3SOX** [comment]
I tested
Qt: Dolphin, Kate, Audacious
Electron: VSCode
GTK: GIMP
Unsure: LibreOffice
and it made no difference running with `KDE_NO_GLOBALMENU=1` set

**Comment by psifidotos** [comment]
env KDE_NO_GLOBALMENU=1 dolphin

**Comment by D3SOX** [comment]
I'm not sure why but this doesn't change anything for me

**Comment by psifidotos** [comment]
ping Plasma devs in that case... This applet has nothing to do with this.
