### ISSUE TITLE
Plasma Spacers and this applet don't work very well together [FIX NEEDED]

### ISSUE THREAD

**Issue by phoenix277yt** [psifidotos/applet-window-appmenu#146]
if i remove the spacer everything just sticks to one side, 
if i remove the appmenu, I wont have the appmenu
and even if the spacer is set to a flexible size it still has the scroll thing.

^^global menu works better than this but i like this so please make fixes.

sorry for bad punctuation im in a hurry, will beautify later.

**Comment by psifidotos** [comment]
Show me what you are trying to achieve

**Comment by phoenix277yt** [comment]
![image](https://user-images.githubusercontent.com/73348506/107605467-3c085400-6c59-11eb-8947-556e003a2f2b.png)
this is what I have right now and am trying to achieve. (I know that global menu will essentially be better but i want scrolling so i have to use this.)
![image](https://user-images.githubusercontent.com/73348506/107605486-4aef0680-6c59-11eb-89fa-4c4eeb136f3c.png)

If I replace global menu with this one this happens, it does not take full space that is given to it, using latte spacer crams it in even more and removing the spacer would cause everything to go to the left.

**Comment by psifidotos** [comment]
1. install latest version from master branch
2. remove any plasma spacers
3. enable in appmenu options: Always use maximum available width
