### ISSUE TITLE
No menu entries for Firefox / Thunderbird

### ISSUE THREAD

**Issue by ahvth** [psifidotos/applet-window-appmenu#147]
Running the applet on Arch Linux, I am able to see Thunderbird / Firefox menus in KDE's own global menu applet, but not in this applet.

Am I missing a dependency or configuration entry in FF/TB or is this unsupported?

**Comment by psifidotos** [comment]
No idea, as long as you get global menu from kde global menu applet you should also get global menu with appmenu also.

**Comment by psifidotos** [comment]
It works just fine in my Tumbleweed system with Firefox.

**Comment by D3SOX** [comment]
The official Mozilla Firefox release does not support the global menu.
The reason that it works in @psifidotos's system is that OpenSUSE provides a patched version (https://build.opensuse.org/package/show/mozilla:Factory/MozillaFirefox)

Here is a good thread on the Manjaro forums that lists several options:
https://forum.manjaro.org/t/howto-enabling-kde-global-menu-support-in-mozilla-firefox-and-thunderbird/7405

**Comment by ahvth** [comment]
Thanks for your replies. I double checked functionality with the default KDE global menu widget, and it seems i incorrectly recalled it working with firefox. @D3SOX 's post sums up why it doesn't work, so I'm going to close this issue.

**Comment by wapsi** [comment]
I just installed fresh Debian 11 and I can verify that the KDE global menu widget is showing the Firefox ESR (both installed from the Debian 11's official repositories) menu correctly but applet-window-appmenu is showing nothing.

Is it possible to implement the support for Firefox menu in applet-window-appmenu?

**Comment by psifidotos** [comment]
No idea, it should just work. At least in my Tumbleweed system Firefox menu works just fine, no idea why it breaks for Debian.

**Comment by wapsi** [comment]
I don't know if the Debian's Firefox ESR is patched with those same patches than openSUSE uses or is it working somehow other? Could there be some Firefox/Thunderbird specific code in KDE's global menu widget?

**Comment by wapsi** [comment]
Actually, I discovered that the KDE's global menu widget is showing the menu of previously focused application when I focus the Firefox window and not the Firefox menu (so this is a bug in KDE global menu). Applet-window-appmenu is correctly showing nothing. So nevermind, this issue should remain as closed.

Thanks!
