### ISSUE TITLE
[Bug Report] Can't work

### ISSUE THREAD

**Issue by BlueQuantumx** [psifidotos/applet-window-appmenu#148]
Can't work in Plasma 5.21.0. It displays nothing.
But when I add the official applet "Global Menu" at the same time, it works very well.
The latest master version also don't work.

**Comment by rodrigopedra** [comment]
I know it is not a proof that there is no bugs, but it is working fine for me

![image](https://user-images.githubusercontent.com/5470108/108853423-7a8cff80-75c5-11eb-9b61-c497d0499f64.png)

As the image implies, I am running KDE Neon.

I also installed it from source using the instructions on this repo's README

**Comment by BlueQuantumx** [comment]
I reinstalled it from AUR, then it works well...
