### ISSUE TITLE
Always visible behavior for Single Menu button and never hide it in that case

### ISSUE THREAD

**Issue by maverick74** [psifidotos/applet-window-appmenu#149]
Would be nice if we have an "Always Visible" option for the Menu Button (like we have for the window buttons).

Having it turning visible/unvisible all the time is an inconsistency for the toolbar layout (and it's making me a bit more crazy :)

**Comment by psifidotos** [comment]
Send me a screenshot please what you are trying to achieve and what you want to be drawn in that case.
If you disable option: "Show only menus from active applications" why this is not enough for you?

**Comment by maverick74** [comment]
@psifidotos Hi, thanks for your reply.

I'll be away from my Linux box until next Monday, only then I can send you a screenshot. Sorry.

But I'll advance the intention:
The intention (still at tests) is to save as much vertical space as possible.
To do that, I've moved the entire taskbar panel to the top of the screen and I've also removed the applications titlebars.
In the top panel I've placed (from left to right):
Plasma menu, application menu (as a single button), taskbar manager, system tray, clock and finally the window control buttons.

Now the window control buttons are always visible but, as I switch between applications (eg: Firefox, dolphin and libreoffice) the menu button keeps coming and going causing taskbar manager to resize constantly (as Firefox does not has it's shown - the same happens if all apps are closed).

Maybe I've overlooked the option you mentioned...

But the intention was to avoid the constant resize of the taskbar.

Thank you

**Comment by psifidotos** [comment]
When you click Firefox that does not have menu items in your system, in my Tumbleweed system works just fine, in that case what disabled buttons will be shown?

**Comment by trmdi** [comment]
> When you click Firefox that does not have menu items in your system, in my Tumbleweed system works just fine, in that case what disabled buttons will be shown?

He wants an option to always show the menu icon. When no menu is available - it is a disabled grayed out.
What he wants to achieve is make it a fixed width stuff on the panel.

**Comment by psifidotos** [comment]
> > When you click Firefox that does not have menu items in your system, in my Tumbleweed system works just fine, in that case what disabled buttons will be shown?
> 
> He wants an option to always show the menu icon. When no menu is available - it is disabled but still appears in some different icon.
> What he wants to achieve is to make it a fixed width stuff on the panel.

Isnt option "Always use maximum available width" doing the desired behavior? what are the side effects?

**Comment by trmdi** [comment]
> Isnt option "Always use maximum available width" doing the desired behavior? what are the side effects?

No, it isn't. With this config:
![image](https://user-images.githubusercontent.com/11857205/109383595-05e5f800-791a-11eb-8c73-ce3c3512b89c.png)

mpv will now show the menu button:
![image](https://user-images.githubusercontent.com/11857205/109383613-1f873f80-791a-11eb-9fe3-416e9b52796c.png)

He wants: the menu button still appears, even if it is disabled.

**Comment by psifidotos** [comment]
Ah... you mean only for the Single AppMenu button scenario! 
now I get it

**Comment by maverick74** [comment]
Yeah. That's it!
Thanks @trmdi for clarifying it.

And thanks @psifidotos for clarifying the title :)

I guess the screenshot won't be needed anymore... But if you want it I can still take it.

**Comment by maverick74** [comment]
As a side-note (because of the bug i submitted at: https://github.com/psifidotos/applet-window-buttons/issues/122) i would like to add that in my opinion the deactivated menu should also preserve it's space even if there is no window/software open/running

**Comment by adrianinsaval** [comment]
+1 to this request, I want to place the menu besides the task manager and it is annoying if it appears and dissappears depending on what app is active. I also think it should preserve the used space when no app is active, the icon could be shown as disabled in that case or even if it's empty reserved space it's fine.

**Comment by adrianinsaval** [comment]
found a solution for this one, in this line:
https://github.com/psifidotos/applet-window-appmenu/blob/d77d03879fc032066ec00d30878742cc7aa83767/package/contents/ui/main.qml#L248
change `HiddenStatus` to `PassiveStatus`
So the request would be to add a config for this or to make that change.

**Comment by maverick74** [comment]
@adrianinsaval Is there any config file on the system where we can also enable this option?

**Comment by maverick74** [comment]
@adrianinsaval Forget my question.

It's in:

`/usr/share/plasma/plasmoids/org.kde.windowappmenu/contents/ui/main.qml
`

Now... Do you have any idea on How To do the same for the window buttons I mentioned above ( psifidotos/applet-window-buttons#122 )???

**Comment by adrianinsaval** [comment]
> @adrianinsaval Forget my question.
> 
> It's in:
> 
> `/usr/share/plasma/plasmoids/org.kde.windowappmenu/contents/ui/main.qml `
> 
> Now... Do you have any idea on How To do the same for the window buttons I mentioned above ( [psifidotos/applet-window-buttons#122](https://github.com/psifidotos/applet-window-buttons/issues/122) )???

Use the always visible option and check the option to draw the buttons inactive state when needed

**Comment by maverick74** [comment]
Yes, but I would prefer the buttons to became invisible (while preserving their space) as when have the windows in their un-maximized state, having the buttons both in the panel and in the window frame becomes redundant.

I know it's a minor detail...

(Also, when all windows are closed if we press the "keep window above others" button and then open any app the button activated until we double-click on it)

**Comment by psifidotos** [comment]
How is that relevant to this bug report? Please comment only for the issue and nothing more.It is not a forum.

**Comment by psifidotos** [comment]
merged

**Comment by maverick74** [comment]
@psifidotos did the merged "solution" also included what i mentioned above?

> If I have the Single Menu button on the window frame - when they are un-maximized - it doesn't make sense to have it also shown in the panel - it's redundant.
> So, ideally, it should became invisible as well _- in the panel -_ while keeping the space empty/preserved

It's not something "essential", but i believe that makes sense to have that option, hence my question... :)

**Comment by psifidotos** [comment]
No, you need a new bug report with details of qhat you are proposing and why
