### ISSUE TITLE
Single button should disappear when no application is focused...

### ISSUE THREAD

**Issue by moffis** [psifidotos/applet-window-appmenu#15]
... instead it stays and and opens the menu of the last focused application

EDIT: 
can be closed. Everything works after latte-dock --replace

EDIT2:
I would like to reopen this. The single button menu stays visible on the plasma desktop when the last window has no menu at all like steam.

**Comment by psifidotos** [comment]
> I would like to reopen this. The single button menu stays visible on the plasma desktop when the last window has no menu at all like steam.

isnt that also the plasma global menu behavior?

**Comment by moffis** [comment]
yeah, the plasma global menu behavior is to **always** show the menu of the last minimized window. As I can see this applet tries to fix that. But the exception is when the last minimized window has no global menu like steam. Then the single button menu is shown on the desktop.

https://streamable.com/c5d0c
