### ISSUE TITLE
Appmenu is not showing at all after latest update 

### ISSUE THREAD

**Issue by dedenrh** [psifidotos/applet-window-appmenu#150]

**Comment by psifidotos** [comment]
Works just fine for me with master branch

**Comment by chaletweb** [comment]
same issue 
appmenu is not showing at all 
distrib : Manjaro kde

**Comment by vannaka** [comment]
Manjaro kde updated to plasma 5.21 over the weekend. Now the appmenu is not working for any application. It might be a plasma problem or it might be this applets problem, who knows.

**Comment by trmdi** [comment]
> Manjaro kde updated to plasma 5.21 over the weekend. Now the appmenu is not working for any application. It might be a plasma problem or it might be this applets problem, who knows.

Try compiling the applet on your own machine. Probably Manjaro has not rebuilt it with new libs.

**Comment by vannaka** [comment]
@trmdi Rebuilding fixed it, thanks!

**Comment by dedenrh** [comment]
Thank you, rebuilding solved the problem.

**Comment by trmdi** [comment]
@psifidotos 
Is there any way to tell package packager rebuild this automatically? E.g. Release a new version whenever a new Plasma released?

**Comment by psifidotos** [comment]
A note in the Readme could be added
 Releasing every time plasma has release sorry I don't have the time to do so.
