### ISSUE TITLE
Menus not visible in virt-manager

### ISSUE THREAD

**Issue by D3SOX** [psifidotos/applet-window-appmenu#151]
### Description
It works at first but I always run into this issue when using `virt-manager` for a while in conjunction with this applet. It just shows a tiny gray area where normally the menu should be. I'm not entirely sure what causes this.

### Video
In this case the problem is at the top level but sometimes it works in the first level but then does the same thing in the second.

https://user-images.githubusercontent.com/24937357/109671046-04b00780-7b74-11eb-84d6-70dc281820cb.mp4

Edit: I got it on the second level now:
![image](https://user-images.githubusercontent.com/24937357/109876808-7f5f4c80-7c72-11eb-9dd9-7186b366eef0.png)

### System Information copied from Info center
Operating System: Arch Linux
KDE Plasma Version: 5.21.2
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.11.4-133-tkg-pds
OS Type: 64-bit
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon ™ RX 480 Graphics

### Applet version
`0.6.0.r0.g7886b78-1` from AUR package `plasma5-applets-window-appmenu-git`

### Additional information
How can I debug this?

**Comment by psifidotos** [comment]
Feel free to report this also at Plasma Global Menu applet.

**Comment by D3SOX** [comment]
I will create an issue at the KDE Bugtracking System
