### ISSUE TITLE
Listen to menu states changes

### ISSUE THREAD

**Issue by iwex** [psifidotos/applet-window-appmenu#153]
Hi! Does this plugin listen to menu changes? Like at the start of the application some menu items can be disabled and after some actions in this app - they will be enabled.
For example, I have a problem with Bitwarden. Some menu items are disabled before login. But After login, they remain disabled.

**Comment by psifidotos** [comment]
I dont know, the same infrastructure with Plasma Global Menu is used. I dont think it tracks enabled / disabled state all the time neither Plasma Global Menu neither that applet.

**Comment by psifidotos** [comment]
when you switch between different applications isnt that updated?

**Comment by iwex** [comment]
No, I even tried to find something in logs, but with no success.

**Comment by psifidotos** [comment]
then it is not this applet responsibility


it is considered: upstream, you probably need to report it to plasma globalmenu

**Comment by iwex** [comment]
@psifidotos where should I find repo of plasma globalmenu?

**Comment by psifidotos** [comment]
https://bugs.kde.org/enter_bug.cgi?product=plasmashell

product: Global Menu
