### ISSUE TITLE
Appmenu is not aligned when a bottom Latte view has a Thickness Margin

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-appmenu#154]
The title says it all.

![image](https://user-images.githubusercontent.com/11857205/111018645-94fc1100-83ec-11eb-8a4a-027debe1c362.png)

It should be center aligned.
Is this a bug or a feature?

**Comment by psifidotos** [comment]
merged, fixed

**Comment by trmdi** [comment]
Still happens in Latte edit mode:
![image](https://user-images.githubusercontent.com/11857205/111024630-66912c80-8412-11eb-89dd-0ff2718b663c.png)
