### ISSUE TITLE
[Compact mode]  Behaviors are still not applied

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-appmenu#156]
Currently, all behaviors are not applied when the applet's in the Compact mode.
![image](https://user-images.githubusercontent.com/11857205/111026636-d22cc700-841d-11eb-9c98-7ce67127dcf2.png)

**Comment by psifidotos** [comment]
I sent fixes for this, are you using latest master?

**Comment by trmdi** [comment]
Yes, I'm using c010eebf358b5e33340f0218db838cb5d6948f5f

There are some issues:

1, In Latte's edit mode, the applet seems bigger than expected, it should not touch the blue margin part. See the picture:
![image](https://user-images.githubusercontent.com/11857205/111032886-0c5b9000-8441-11eb-9340-64950cf44e04.png)

It's not a real issue but it looks different with other widgets.

**Comment by psifidotos** [comment]
@trmdi you mean that always use maximum available width should be disabled in compact mode, right?

**Comment by trmdi** [comment]
2, About the Behavior:
2.1. "Always use max available width": I don't see any different when choose or not choose it.

**Comment by trmdi** [comment]
> @trmdi you mean that always use maximum available width should be disabled in compact mode, right?

Yes, but I'm not sure, is there any use case that need it? Currently it does not work. We can make it work, or just disable that option.

**Comment by psifidotos** [comment]
> > @trmdi you mean that always use maximum available width should be disabled in compact mode, right?
> 
> Yes, but I'm not sure, is there any use case that need it? Currently it does not work. We can make it work, or just disable that option.

I disabled that one

**Comment by trmdi** [comment]
Ok, and what about the remain Behavior? Show WIndow Title applet on mouse exit? Disable it or make it work?

**Comment by trmdi** [comment]
> Yes, I'm using [c010eeb](https://github.com/psifidotos/applet-window-appmenu/commit/c010eebf358b5e33340f0218db838cb5d6948f5f)
> 
> There are some issues:
> 
> 1, In Latte's edit mode, the applet seems bigger than expected, it should not touch the blue margin part. See the picture:
> ![image](https://user-images.githubusercontent.com/11857205/111032886-0c5b9000-8441-11eb-9340-64950cf44e04.png)
> 
> It's not a real issue but it looks different with other widgets.

Ok, the remain issue is this. Do I need to open a new issue?

**Comment by psifidotos** [comment]
Unfortunately this is not an appmenu and in general Latte does not solve this and I dont know if it will in the future. the screenshot shows that your bottom right applets are too many and exceed the size that is available, so Latte what could do about it?

**Comment by trmdi** [comment]
Oh no, just mean these red regions, why does it look different with the others?
![image](https://user-images.githubusercontent.com/11857205/111034865-20f05600-844a-11eb-8acf-1dca6619f113.png)

**Comment by psifidotos** [comment]
> Oh no, just mean these red regions, why does it look different with the others?
> ![image](https://user-images.githubusercontent.com/11857205/111034865-20f05600-844a-11eb-8acf-1dca6619f113.png)

this is intentional. this way are identified the applets that CanFillArea : https://api.kde.org/frameworks/plasma-framework/html/classPlasma_1_1Types.html

There are three different paddings based on Plasma 5.21:
1. CanFillArea applets such as AppMenu, Plasma Taskmanager, Plasma Icon-Only taskmanager etc. these are applets that are occupying entire thickness and take responsibility on their own what padding to provide
2. Normal applets that provide normal Thickness margin. This is the case for most applets
3. Smaller padding than [2], these are applets are between MarginAreasSeparators  and become even smaller than [2] this technique is used from plasma default panel to provide smaller icons for its systray. Info can be observed at: https://www.youtube.com/watch?v=nWWPQ2RgoI4

**Comment by trmdi** [comment]
Got it, thank you so much for your explanation. <3
