### ISSUE TITLE
Install dependencies wrong on Fedora

### ISSUE THREAD

**Issue by Uldreth** [psifidotos/applet-window-appmenu#159]
I have attempted to install this applet on Fedora 34 (KDE Spin, Xorg). Before doing so, I have installed the dependencies listed in the INSTALLATION.md file. The applet did not compile due to missing dependencies.

I had to install the kf5-kitemmodels-devel, plasma-workspace-devel and kf5-kwayland-devel packages, after which the applet compiled and is working as intended.

Please update the INSTALLATION.md file with the required dependencies!

**Comment by psifidotos** [comment]
> Please update the INSTALLATION.md file with the required dependencies!

In ALL my projects `INSTALLATION.md` in maintained only from community. Please send a PR that updates it for Fedora and I will  accept it of course.

**Comment by Uldreth** [comment]
I am no programmer and am quite unfamilar with git so it will take me some time to figure out how, but sure.
