### ISSUE TITLE
Single button menu is clickable even if application has no menu

### ISSUE THREAD

**Issue by moffis** [psifidotos/applet-window-appmenu#16]
The behaviour is depicted in the video.
Steam has no menu, but still it is able to click the single button menu. It then stays toggled until clicked again.

[2018-11-21 15-23-21.flv.zip](https://github.com/psifidotos/applet-window-appmenu/files/2604564/2018-11-21.15-23-21.flv.zip)

**Comment by moffis** [comment]
I will test today.

**Comment by moffis** [comment]
cannot test because plasma global menu crashes latte dock

**Comment by moffis** [comment]
does not happen with plasma global menu.

[2018-11-21 16-39-28.flv.zip](https://github.com/psifidotos/applet-window-appmenu/files/2604825/2018-11-21.16-39-28.flv.zip)

**Comment by trmdi** [comment]
@moffis 
A tip: you could record the screen in the `mp4` format and anonymously upload it to https://streamable.com/
That would help others to see your video more easily and quickly.
