### ISSUE TITLE
scrolling dont work 

### ISSUE THREAD

**Issue by agent188** [psifidotos/applet-window-appmenu#164]
![изображение](https://user-images.githubusercontent.com/41228098/122454729-5c07a580-cfb4-11eb-9e76-e102c72323d6.png)

![изображение](https://user-images.githubusercontent.com/41228098/122454800-69249480-cfb4-11eb-952e-39e6d99272ee.png)

![изображение](https://user-images.githubusercontent.com/41228098/122454882-793c7400-cfb4-11eb-81dd-1deb74af6bcd.png)

**Comment by psifidotos** [comment]
Scrolling in plasma has been disabled. I couldnt make it to work in any case. It works only with latte panels.

**Comment by agent188** [comment]
Scrolling was disabled in the source code?

**Comment by psifidotos** [comment]
Yes and also on calculations, at some point when plasma introduced centered widgets scrolling did not work as expected, so it was dropped.
