### ISSUE TITLE
LibTaskManager not found in Fedora

### ISSUE THREAD

**Issue by AwesomeKenP** [psifidotos/applet-window-appmenu#166]
When building, I get the following error:
....
....`
In file included from /home/kplaha/Downloads/KDE/applet-window-appmenu-0.7.0/plugin/wm/waylandwindowmanager.h:33,
                 from /home/kplaha/Downloads/KDE/applet-window-appmenu-0.7.0/plugin/wm/waylandwindowmanager.cpp:20:
/usr/include/KF5/KWayland/Client/plasmawindowmanagement.h:494:13: note: declared here
  494 |     quint32 internalId() const;
      |             ^~~~~~~~~~
[100%] Linking CXX shared library libappmenuplugin.so
/usr/bin/ld: cannot find -lPW::LibTaskManager
collect2: error: ld returned 1 exit status
make[2]: *** [plugin/CMakeFiles/appmenuplugin.dir/build.make:227: plugin/libappmenuplugin.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:316: plugin/CMakeFiles/appmenuplugin.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
[  3%] Built target org.kde.windowappmenu-plasmoids-metadata-json
[  6%] Automatic MOC for target plasma_applet_windowappmenu
[  9%] Built target plasma_applet_windowappmenu_autogen
Consolidate compiler generated dependencies of target plasma_applet_windowappmenu
[ 21%] Built target plasma_applet_windowappmenu
[ 24%] Automatic MOC for target dbusmenuqt
[ 24%] Built target dbusmenuqt_autogen
Consolidate compiler generated dependencies of target dbusmenuqt
[ 54%] Built target dbusmenuqt
[ 57%] Automatic MOC for target appmenuplugin
[ 57%] Built target appmenuplugin_autogen
Consolidate compiler generated dependencies of target appmenuplugin
[ 60%] Linking CXX shared library libappmenuplugin.so
/usr/bin/ld: cannot find -lPW::LibTaskManager
collect2: error: ld returned 1 exit status
make[2]: *** [plugin/CMakeFiles/appmenuplugin.dir/build.make:227: plugin/libappmenuplugin.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:316: plugin/CMakeFiles/appmenuplugin.dir/all] Error 2
make: *** [Makefile:146: all] Error 2`

I cannot find any library matching that for Fedora. Is it possible to build the applet/widget under Fedora? If so, which package provides the above library?

Thanks.

**Comment by psifidotos** [comment]
libtaskmanager is part of plasma-workspace-dev

**Comment by AwesomeKenP** [comment]
plasma-workspace-devel is already installed:
`dnf install -y plasma-workspace-devel.x86_64
Last metadata expiration check: 0:33:51 ago on Sat 03 Jul 2021 07:15:35.
Package plasma-workspace-devel-5.22.2.1-1.fc34.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!`

**Comment by AwesomeKenP** [comment]
Hi,

On Fedora, the package is `plasma-workspace-devel` and it is already installed:
`dnf install -y plasma-workspace-devel.x86_64`
`Last metadata expiration check: 0:33:51 ago on Sat 03 Jul 2021 07:15:35.`
`Package plasma-workspace-devel-5.22.2.1-1.fc34.x86_64 is already installed.`
`Dependencies resolved.`
`Nothing to do.`
`Complete!`

What else can I check?

**Comment by trmdi** [comment]
Try installing all BuildRequires listed here: https://src.fedoraproject.org/rpms/latte-dock/raw/f30/f/latte-dock.spec

**Comment by 2shrestha22** [comment]
@AwesomeKenP `sudo dnf install kf5-kitemmodels-devel`

**Comment by gif-prog** [comment]
It worked for me.

I installed both **kf5-kitemmodels-devel** and **plasma-workspace-devel**
