### ISSUE TITLE
Compiling on Fedora

### ISSUE THREAD

**Issue by AwesomeKenP** [psifidotos/applet-window-appmenu#167]
I had raised another similar issue but that was closed with a comment that I should install `plasma-workspace-dev`.

The package on Fedora is called `plasma-workspace-devel`. However, that did not help and I got the same error.

I finally edited build files and got it working as follows:

The `libtaskmanager.so` is located at `/usr/lib64/libtaskmanager.so`. 

I edited `applet-window-appmenu-0.7.0/build/plugin/CMakeFiles/appmenuplugin.dir/link.txt`, removed `-lPW::LibTaskManager`, and added `/usr/lib64/libtaskmanager.so`.

Then, I ran `sudo make install` inside build directory (not `install.sh`).

Maybe this could help you (or someone else) with the build on Fedora.

Cheers.

**Comment by psifidotos** [comment]
you can try to add these information that INSTALLATION.md file with a MR request
