### ISSUE TITLE
AppMenu not showing on my Arch setup

### ISSUE THREAD

**Issue by YamiYukiSenpai** [psifidotos/applet-window-appmenu#168]
I have Wayland on both Neon Unstable and Arch.  The former works fine, while the latter just shows "Window AppMenu" while the settings page for the plasmoid is open.  I was only able to do that just now while trying to open this issue.  Before, nothing would show, until I "edit" the dock, and opened the settings for the AppMenu.  

![AppMenu settings](https://user-images.githubusercontent.com/13153124/124375532-b8371e80-dc70-11eb-98f8-ee4406952547.png)
![Dolphin](https://user-images.githubusercontent.com/13153124/124375549-ce44df00-dc70-11eb-9ad8-85b1d979680d.png)

I tried to use the hamburger button instead of the global menu, but that didn't work either.

**Comment by psifidotos** [comment]
Which appmenu version are you using and how did you retrieve it?

**Comment by YamiYukiSenpai** [comment]
> Which appmenu version are you using and how did you retrieve it?

0.7.0 from the release page

**Comment by psifidotos** [comment]
are you using Arch version or do you build it by yourself?

**Comment by YamiYukiSenpai** [comment]
> are you using Arch version or do you build it by yourself?

Can you clarify?

I'm not sure if this is what you're asking, but the only difference between my Plasma on Arch and the default is that I'm using [KWinFT](https://gitlab.com/kwinft/), and I had to build KDecoration from Git (to fix an issue with the former).

**Comment by psifidotos** [comment]
nothing to do. In any case, where did you find your AppMenu applet for your Arch system?

**Comment by YamiYukiSenpai** [comment]
From the release page on GitHub

**Comment by psifidotos** [comment]
in any case that makes it a distro issue and not related to general development

**Comment by hsantanna** [comment]
> > are you using Arch version or do you build it by yourself?
> 
> Can you clarify?
> 
> I'm not sure if this is what you're asking, but the only difference between my Plasma on Arch and the default is that I'm using [KWinFT](https://gitlab.com/kwinft/), and I had to build KDecoration from Git (to fix an issue with the former).

It seems that KWinFT does not support global menu on Wayland yet, and waits for this merge request:
https://gitlab.com/kwinft/kwinft/-/merge_requests/78

Are you using KWinFT and Wayland on both, Neon and Arch?

Did you tested AppMenu with main KWin?

How does the official KDE Plasma Global Menu?

I'm using Plasma on Wayland for months and global menu works great, no matter if with AppMenu or with Global menu widget.

**Comment by YamiYukiSenpai** [comment]
> > I'm not sure if this is what you're asking, but the only difference between my Plasma on Arch and the default is that I'm using [KWinFT](https://gitlab.com/kwinft/), and I had to build KDecoration from Git (to fix an issue with the former).
> 
> It seems that KWinFT does not support global menu on Wayland yet, and waits for this merge request:
> https://gitlab.com/kwinft/kwinft/-/merge_requests/78
> 
> Are you using KWinFT and Wayland on both, Neon and Arch?

Just Arch

> Did you tested AppMenu with main KWin?

Yes, and it works in KWin.  I opened [an issue](https://gitlab.com/kwinft/kwinft/-/issues/167) for it.

**Comment by misketmuskat** [comment]
I am having similar problem. I installed plasma5-applets-window-appmenu from AUR, however I cannot find the applet on widget list.
