### ISSUE TITLE
Menu overlapping with justified widget

### ISSUE THREAD

**Issue by atlas-ark** [psifidotos/applet-window-appmenu#169]
Not sure about that, but some time ago menu scrolling (for appmenus that don't fit in the reserved space) was working good:

![image](https://user-images.githubusercontent.com/37074205/124749738-e775b600-df24-11eb-8125-f88ad2e8334c.png)

My actual layout (note justifiers):
![image](https://user-images.githubusercontent.com/37074205/124750153-6965df00-df25-11eb-84e7-1c3b2d8b15c3.png)

Thank you in advance

**Comment by psifidotos** [comment]
you need to enable in appmenu settings: **Always use maximum available width**

**Comment by felagund** [comment]
That setting makes the menu be cropped from the right. That is more aesthetically pleasing than the screenshot above, but from a usability perspective (and even aesthetica one), I (and I think maybe not jsut me) would prefer if the justified widget would be justified in the empty space between the appmenu and the next widget on the other side. It would make all of the menu accessible and the diget in questino would be more prominent if it had space on both its sizes.

In plain language, on the screenshot above, it would mean that clock would be centered between the rightmost edge off appmenu on the left and system tray on the right. Especially if that widget in question is Applet Window Title, that would make a lot of sense to me. Not sure if this would need changes to the latte panel.
