### ISSUE TITLE
Clicking on the edge and custom shortcut opens empty popup

### ISSUE THREAD

**Issue by moffis** [psifidotos/applet-window-appmenu#17]
Clicking on the edge is demonstrated in the video. I cannot reproduce in plasma global menu.

https://streamable.com/692fd

The same when using a custom shortcut. This also happens in plasma global menu

After this empty popups appears the first time latte panel shadow won't go away.

**Comment by psifidotos** [comment]
Can you reproduce when instead of a single button the entire menu is shown?

**Comment by moffis** [comment]
No, both clicking on the edge and shortcut only happens in single button menu
