### ISSUE TITLE
"Show only menus from current screen" on Virtual Desktops

### ISSUE THREAD

**Issue by rodrigopedra** [psifidotos/applet-window-appmenu#172]
I think this is similar to what was described in #170 and fixed on 941effce4c538c15486a19986a71586b3527cdd1

But when changing Virtual Desktops the menus from inactive screens are still retained.

https://user-images.githubusercontent.com/5470108/125994288-a8cbf2bb-3b7a-4366-8292-0da18b90a924.mp4

If you provide some guidance I can try to make a PR. But I am not familiar with the code base.

**Comment by psifidotos** [comment]
You need to provide full details

**Comment by psifidotos** [comment]
Latte or plasma panel?

**Comment by rodrigopedra** [comment]
It is the same setup I sent on #170 

- KDE Neon (updated)
- The top panel is a Latte dock (updated today from git before video)
- applet-window-apmenu (last git version)
-

**Comment by psifidotos** [comment]
wayland or x11?

**Comment by rodrigopedra** [comment]
x11

**Comment by psifidotos** [comment]
that is a Latte issue and pretty hard to solve... Tracking windows based on their activeness per panel/activity/vd/screen and keep track also of its history based on the previous combo...

all the codepath points to Latte LastActiveWindow codepath... so its implementation should first be able to handle this... and then check if that bug is still valid....

no idea if I manage to support such thing for Latte v0.10

**Comment by psifidotos** [comment]
@rodrigopedra managed to implement this... Hard work but I think now LastActiveWindow(LAW Latte code) is more maintainable and provides that experience you are hunting.... Inactive VDs/Activities/Screens etc.. should be tracked properly. Of course LAW code is only Latte related and Plasma codepath from my applets I dont think it can support such complexity for inactive VDs/Screens/Activities etc...

You need to update to latest Latte git version.

https://invent.kde.org/plasma/latte-dock/-/commit/f1d435a38e7184978f2734471c8e6a4dfd214e6f

**Comment by psifidotos** [comment]
@rodrigopedra please test it and report back your findings... That commit is very important because it will probably delay the Latte v0.10 stable release.

**Comment by rodrigopedra** [comment]
@psifidotos thanks a lot. It seems to be working great.

https://user-images.githubusercontent.com/5470108/126055183-21ab9074-07ac-4540-b7c4-46ad78c955b5.mp4

**Comment by psifidotos** [comment]
It seems so natural when it is working correctly and it was so demanding to be implemented...

**Comment by rodrigopedra** [comment]
Been there, thanks a lot for your hard work =)
