### ISSUE TITLE
Can you please list dependencies needed to build it?

### ISSUE THREAD

**Issue by danielkrajnik** [psifidotos/applet-window-appmenu#173]
please?

**Comment by psifidotos** [comment]
they are listed in requirements section of readme file

**Comment by danielkrajnik** [comment]
thanks for the reply, I realize that it's an extremely noobie question, but is there a way to translate "Quick Widgets DBus" and others into apt-specific packages? I know that it can be googled eventually, but given the target audience it would be really nice not having to go through all that

**Comment by psifidotos** [comment]
Installation file is distro packagers and users responsibility to maintain. You can try to ping them.
