### ISSUE TITLE
Problems about appmenu

### ISSUE THREAD

**Issue by goat1515** [psifidotos/applet-window-appmenu#174]
can't move my cursor to the right panel of the first row
The GIF shows that:[https://imgur.com/TsuDUyT](https://imgur.com/TsuDUyT)

**Comment by psifidotos** [comment]
I dont have this problem.

1.Are you using latte or plasma panels?
2. Do you have the same issue with plasma global menu?

**Comment by psifidotos** [comment]
Latte is smart enough to provide enough information to solve this.
1. Make sure you are using at least Latte v0.10 or greater
2. User latest master branch from this applet in order for this to be fixed in your system

**Comment by goat1515** [comment]
> I dont have this problem.
> 
> 1.Are you using latte or plasma panels?
> 2. Do you have the same issue with plasma global menu?

My OS is Manjaro 21.1.0 Pahvo. I'm using KDE 5.85.0 / Plasma 5.22.4 and the AppMenu is on latte panel.
The global menu doesn't have this problem.
My latte is v0.10.0 and the AppMenu is 0.7.1

**Comment by psifidotos** [comment]
Plasma panel does not have this issue because it does not offer custom panel shadow size.

The issue is fixed, you just need to use latest master version of appmenu applet

**Comment by goat1515** [comment]
@psifidotos Yes, there's no issue with plasma panel.
But, I'm using latte top panel, and there's the issue...

**Comment by psifidotos** [comment]
Update your appmenu

**Comment by goat1515** [comment]
@psifidotos I installed it several days ago(with pacman). And its version is 0.7.1-2.
You mean I should reinstall it from the master branch?
And one more thing, how to get rid of the capital letter and the bracket of every menu button?

**Comment by psifidotos** [comment]
1. If you cant wait for 0.7.2 you need to switch to master branch
2. What do you mean about capital letter and bracket?

**Comment by goat1515** [comment]
@psifidotos 
![图片](https://user-images.githubusercontent.com/68107073/130317609-bf9923ad-ce85-4b44-a78c-58e5845734fd.png)
These things. The global menu doesn't have it.

**Comment by psifidotos** [comment]
I dont have them

![εικόνα](https://user-images.githubusercontent.com/2216474/130317806-0ef80a99-3fa7-4b99-8c24-a203c832f33a.png)

**Comment by goat1515** [comment]
@psifidotos Well, maybe because of the translation? But the Global Menu doesn't have it...
Anyway, thank you a lot!!
