### ISSUE TITLE
Can you please list the definitive names of the dependencies for Ubuntu/Debian?

### ISSUE THREAD

**Issue by coldspark29** [psifidotos/applet-window-appmenu#175]
I can't seem to find the right dependencies to build this. There are hundreds of Qt packages on Ubuntu. Can you please make a list? It would probably be good to document them for the other major distros too

**Comment by psifidotos** [comment]
Installation.md file is community responsibility to update

**Comment by coldspark29** [comment]
Thanks, I didn’t see that.
