### ISSUE TITLE
Cannot install from KDE Store

### ISSUE THREAD

**Issue by feldim2425** [psifidotos/applet-window-appmenu#179]
I wasn't able to install the latest version from the KDE store using the "Download new plasma widget" feature. 
When using this feature a Error will occur.
Downloading the plasmoid and using "Installing from local file" also doesn't work however no error appeared, the widget just didn't show up.

Error Message:
![image](https://user-images.githubusercontent.com/6705744/139694666-a1241c98-7e7b-45c6-97eb-8f711dc96fcf.png)

**Comment by psifidotos** [comment]
The applet needs to be built and installed manually or you need to find it a package from your distro that provides it.
