### ISSUE TITLE
what about opening the menubar as a popup at cursor position?

### ISSUE THREAD

**Issue by ripefig** [psifidotos/applet-window-appmenu#18]
A single-key shortcut (like the alt key) triggers a nice big popup with the menu right where the mouse is. it would be great in conjunction with sloppy focus.

I think this could actually be a better idea than any global or local menu: 

* It wouldn't tie users to the top panel, allowing them to use the top edge for whatever they want.
* It would reduce the amount of mousing. 
* It could make the top-level menu items as big as needed, making them easier to hit.
* In conjunction with sloppy focus (or equivalent), it could show the menu that's actually relevant to the window under the mouse, allowing it to be used as a local menu.
* It would save space.
* It would make applications without menubars visually consistent with those that have them.

I understand this isn't strictly relevant to the latte project, but I think it's a pretty good solution.

**Comment by psifidotos** [comment]
totally unrelated to this project...

**Comment by ripefig** [comment]
might be relevant to the plasmoid. but ok.
