### ISSUE TITLE
Appmenu is not visible after upgrading Plasma to 5.23.2

### ISSUE THREAD

**Issue by misketmuskat** [psifidotos/applet-window-appmenu#180]
Hello there,
I was using Window Appmenu Applet on default plasma panel. After upgrading Plasma to 5.23.2, the applet started showing blank. I mean when I enter edit mode, applet is definitely there, but doesn't show any menu.

Global menu widget works tho.

**Comment by psifidotos** [comment]
maybe you need to rebuild it and reinstall it.

**Comment by NICHOLAS85** [comment]
Can confirm that the applet started functioning again after rebuilding and reinstalling
