### ISSUE TITLE
Menu not showing for DaVinci Resolve, but also hiding menubar in window

### ISSUE THREAD

**Issue by fischer-felix** [psifidotos/applet-window-appmenu#181]
I have this problem, where pretty much all applications perform as expected, but DaVinci Resolve neither gets picked up by the applet in latte dock, nor does it draw the menubar in its own window (see the pictures for examples).
Now this is quite a big deal, as almost all the settings you need for a project are in the menubar, so I wonder if there is a way to fix or easier, just blacklist Resolve here?

**Window AppMenu enabled, Dolphin**
![Screenshot_2021 11 11_18:51:19](https://user-images.githubusercontent.com/65448408/141345784-c5c18ede-2df0-476f-9ec4-ed1ebd6567f2.png)

**Window AppMenu enabled, DaVinci Resolve**
![Screenshot_2021 11 11_18:51:40](https://user-images.githubusercontent.com/65448408/141345945-666b1e30-bd4c-4f69-824a-04b973bb14b4.png)

**Window AppMenu removed from latte, DaVinci Resolve**
![Screenshot_2021 11 11_18:53:16](https://user-images.githubusercontent.com/65448408/141345999-9cd1cdc7-da98-42c3-bbcf-2ee923c43517.png)

**Comment by psifidotos** [comment]
Is this reproducable with Plasma Global Menu?

**Comment by fischer-felix** [comment]
Yes, it is indeed 100% the same behaviour.

**Comment by psifidotos** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.reddit.com/r/kde/comments/c55q4x/is_there_any_way_to_disable_global_menu_for_a/&ved=2ahUKEwj5tJOQkZH0AhUBQ_EDHT_rCgcQjjh6BAgDEAE&usg=AOvVaw3AjW7EjtMRP2l6vuJLU3xj

It is upstream issue then. Use the link to disable appmenu for specific application.

**Comment by fischer-felix** [comment]
ευχαριστώ πολύ

**Comment by fischer-felix** [comment]
Sorry to reopen this, but after adding this environment variable, I still don't get a menubar in the app window, and trying it on krita, without it, it shows up in Window AppMenu, however with the variable, it does not show there anymore, but also not in the window itself.
