### ISSUE TITLE
Link installation.md in readme

### ISSUE THREAD

**Issue by hugeblank** [psifidotos/applet-window-appmenu#182]
spent a solid hour looking for how to install the kde frameworks stuff only to find there's a one liner. I think I would have caught it if there was something on the readme that linked to the installation.md page.

**Comment by psifidotos** [comment]
instalation.md file is the default way to find installation steps for plenty of projects

**Comment by hugeblank** [comment]
... surely it couldn't hurt to just link it? I get your point, and maybe it is my fault, but it's a trivial amount of effort to link it to the first thing users read.
