### ISSUE TITLE
[feature] show for most recently active window

### ISSUE THREAD

**Issue by Hate9** [psifidotos/applet-window-appmenu#183]
Similar to how it functions with the "Show only menus from active applications" setting disabled, but the menu stays up if another application on a different screen becomes active.
Same functionality as [/applet-window-buttons/issues/153](https://github.com/psifidotos/applet-window-buttons/issues/153) and [/applet-window-title/issues/122](https://github.com/psifidotos/applet-window-title/issues/122)

**Comment by psifidotos** [comment]
1. Are you using Latte or Plasma panels?
2. Show me a screenshot of your applet settings window

**Comment by Hate9** [comment]
I'm using Plasma panels
I can totally show you a screenshot, but to be clear, this isn't a bug report, it's a feature request.

**Comment by psifidotos** [comment]
I can not implement this for plasma panels because it needs too mush ground work in order to support this with Plasma LibTaskmanager way of things.
It is already supported for Latte through Latte internal LastActiveWindow interface.
The best results are produced with Latte v0.10.4 or greater.

**Comment by Hate9** [comment]
oh, really? I may have to finally check out Latte then
