### ISSUE TITLE
[plasma 5.24] - menus are located out of place

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/applet-window-appmenu#189]
1. Menus show up way more below the panel, as if there was some invisible space. After some moment, menus start to show up normally, touching the panel. It's as if menus couldn't decide what position to take and at first they are far away from the panel, but then they start to show up more correctly.
2. After some time, menus stopped showing up. Moreover, first appmenu on firefox-appmenu-bin and thunderbird-appmenu-bin didn't work. Now that menus on, for example Dolphin, stopped showing up, menus on firefox and thunderbird showed up. Restarting latte didn't help. This is confusing.
3. When moving through menus, the whole screen flickers: everything becomes lighter than goes back to normal state.

I already recompiled latte-dock-git and this extension, restarted latte, but the issue persists. I already tried to use the Plasma appmenu applet, but it has some color problems, so your applet is the only one working with latte correctly, or at least that was the case before. After the update, it's broken.

**Comment by psifidotos** [comment]
1. I suppose you mean 5.24
2. I will take a look after I update to 5.24 in my Tumbleweed system.

Currently I am working on different development areas

**Comment by michaldybczak** [comment]
Sorry, yeah I meant 5.24.

After system reboot, appemnu for Dolphin and Firefox shows. However, the bug with menus once being away from the panel and once correctly still applies.

Besides, latte was super unstable and crashed several times. I had to recompile it, and now it seems to be fine. I know that this is not a place to write about latte, but this all is probably somehow connected. Plasma 5.24 added many changes in areas that affect latte, appmenu, buttons (there is an issue with it too, I'll submit it in another thread).

Here is the screenshot with menu being apart of the panel.

![Screenshot_20220209_205814](https://user-images.githubusercontent.com/10132958/153281077-d31009ac-75fe-49c6-ad28-beaaa89b11bc.jpeg)

As to the flickering bug, change to some dark theme, preferably use kqvantum theme, then maximize Dolphin and move cursor over the menu. The flickering is caused by theming changes, not the screen brightness changes. So on Firefox this flickering is not visible, since the window's content is not using much of theming elements.

If necessary, I can create a short video showing this flickering effect.

Because of Plasma upgrade, not only me will be experiencing issues, so this is always a time when people will be bugging you. Sorry about that, because I understand how irritating is to change focus when your mind and energy is elsewhere.

Plus, there is some minor theming/coloring bug with systray, so it probably needs also an upgrade and another issue thread.

New Plasma, new problems... ;).

**Comment by psifidotos** [comment]
I keep only the menus location issue, anything else is out of place.

**Comment by michaldybczak** [comment]
OK, that's fair.
The out of place menu shows up when we activate it for the first time. Usually, when we move the cursor over menu element again, it's no longer out of place.

So to trigger it, open a new app, click on one menu and move the cursor over others. To trigger it anew, open some other app, and so on.

**Comment by aliquo93** [comment]
I can confirm the same behavior on Plasma 5.24 and latte dock 0.10.8, but it was also happening on Plasma 5.22/5.23 and previous latte dock versions.

**Comment by psifidotos** [comment]
#177
