### ISSUE TITLE
Menu entries (File, Edit, etc) don't follow universal font settings.

### ISSUE THREAD

**Issue by ChrisP4** [psifidotos/applet-window-appmenu#19]
Fonts set in system settings are not being followed by this widget.

**Comment by psifidotos** [comment]
of course they do, because it uses PlasmaComponents.Label which is responsible for this... You probably have the same issue with all plasmoids so you must report your bug at plasma bug tracker...

**Comment by psifidotos** [comment]
first make sure that you have a bug, at the following window the General font is the one you are searching...
In my system updating the General font updates directly all applets showing texts

![default](https://user-images.githubusercontent.com/2216474/48971446-78bce600-f022-11e8-98b5-ef3d092b1469.png)

**Comment by ChrisP4** [comment]
Yes, my general fonts are Cantarell: 
![screenshot_20181124_230353](https://user-images.githubusercontent.com/14283056/48972930-6e5c1580-f03d-11e8-9528-8459f01159d8.png)

But as you can see here the global menu widget (on the desktop) doesn't follow my general fonts.
On the panel the menu is from active window control and i've set it manually to cantarell:
![screenshot_20181124_230438](https://user-images.githubusercontent.com/14283056/48972936-8b90e400-f03d-11e8-9d07-2575ce2f61bc.png)

**Comment by trmdi** [comment]
@ChrisP4
To my eyes they look the same. Try changing to another more special font to compare.

**Comment by ChrisP4** [comment]
Yes, they do change. My bad.
