### ISSUE TITLE
not working with firefox-appmenu

### ISSUE THREAD

**Issue by CarrotDLaw** [psifidotos/applet-window-appmenu#191]
The appmenu of firefox-appmenu on AUR doesn´t show. However, if this widget and the KDE Global Menu widget are both enabled on the panel, it works properly.

**Comment by psifidotos** [comment]
you need a distro that have patched firefox to provide its appmenu

**Comment by CarrotDLaw** [comment]
firefox-appmenu on AUR is a patched firefox that provides appmenu and it works well with KDE Global menu.

**Comment by CarrotDLaw** [comment]
Turns out that the appmenu-gtk-module package was missing. It's now working properly with both Qt and GTK apps.
