### ISSUE TITLE
Missing `Maximize/restore active window on mouse wheel up/down` feature

### ISSUE THREAD

**Issue by alexdelorenzo** [psifidotos/applet-window-appmenu#192]
Hi @psifidotos , thanks for releasing `applet-window-appmenu` and Latte Dock, I use them all of the time and they're great.

When using Window AppMenu widget on a Latte panel, the `Maximize/restore active window on mouse wheel up/down` setting is missing from its `General > Behavior` preference pane.

However, when using Window AppMenu on a Plasma panel, the `Maximize/restore active window on mouse wheel up/down` feature can be toggled.

I've moved over from Plasma panels to using Latte, and I used this feature a lot when using the widget with Plasma panels.

![appmenu](https://user-images.githubusercontent.com/3579286/153808583-4a9e21c0-10bd-4423-8363-5c4c7b51ffee.png)

**Comment by psifidotos** [comment]
they miss because Latte provides them at Behavior advanced settings
