### ISSUE TITLE
Can't use mouse to select submenus because the Appmenu mouse position tracking takes precedence

### ISSUE THREAD

**Issue by csolisr** [psifidotos/applet-window-appmenu#194]
If I attempt to use the Appmenu on its default mode to select a menu item, then scroll to a submenu, and then scroll to the right to select a submenu item, the applet takes precedence over the submenu and instead opens the next parent menu instead. For example:

- An application has four options: File, Edit, Tools, Help
- I click on File, then on Recent Documents
- I move the mouse towards the right, to select one of the recent documents
- Instead of selecting the document, the Appmenu moves to the Edit submenu and displays that instead

The current workaround is to use the "use single button for application menu", but that defeats the purpose of my current layout.

**Comment by psifidotos** [comment]
what is your applet version? this is not reproducable in my system...

**Comment by csolisr** [comment]
After updating Arch Linux and checking the settings of Latte Dock, I'm no longer able to reproduce it either. Chances are it was fixed with an upgrade of either of those. Closing for now.
