### ISSUE TITLE
Implement Wayland specific features from Plasma's default Global Menu

### ISSUE THREAD

**Issue by ryu-ketsueki** [psifidotos/applet-window-appmenu#196]
I love your appmenu applet. It blends in so well with latte panels and the color stuff. But sometimes I miss some Wayland specific features, like the Search button. Perhaps would be a good idea to see what else the global menu from plasma got working to bring over to your appmenu

**Comment by psifidotos** [comment]
I dont use wayland so I am not really interested yet. Also I am not interested discovering on my own what Plasma Global Menu has added its code.

Best thing you can do is for each feature you are missing is to open a different issue and I will tag them as wayland staff... If anyone is interested to provide merge requests no objection from me.

**Comment by Vistaus** [comment]
> I love your appmenu applet. It blends in so well with latte panels and the color stuff. But sometimes I miss some Wayland specific features, like the Search button. Perhaps would be a good idea to see what else the global menu from plasma got working to bring over to your appmenu

What do you mean? The global menu from Plasma itself doesn't even work on Wayland.

**Comment by ryu-ketsueki** [comment]
> > I love your appmenu applet. It blends in so well with latte panels and the color stuff. But sometimes I miss some Wayland specific features, like the Search button. Perhaps would be a good idea to see what else the global menu from plasma got working to bring over to your appmenu
> 
> What do you mean? The global menu from Plasma itself doesn't even work on Wayland.

What version are you on? Because it is working for several versions now. I think ever since 5.18. Also make sure your distro packages all the D-bus system and session bus.

**Comment by Vistaus** [comment]
> What version are you on? Because it is working for several versions now. I think ever since 5.18. Also make sure your distro packages all the D-bus system and session bus.

I'm on 5.26 on openSUSE Tumbleweed, so everything is already as new as possible. It has never worked for me on Wayland, not on 5.24 and 5.25 either. Multiple people on Reddit have also reported it not working on several Wayland distros.

**Comment by ryu-ketsueki** [comment]
![Spectacle_20221225_193837](https://user-images.githubusercontent.com/39316730/209483535-3517179b-fbee-4fbd-81e7-05c91f332db9.png)
I'm also on Tumbleweed and same version of Plasma. It works as expected for me. It's why I also asked you to check you have the correct bus packages installed. So far I could test even Flatpak ones and they make use of the session bus as expected.
