### ISSUE TITLE
Can't find widget after installing

### ISSUE THREAD

**Issue by TCMOREIRA** [psifidotos/applet-window-appmenu#197]
After installing all dependencies and installing the '.sh' file using the terminal, even though the terminal output said the installation was successful, I couldn't find the widget itself (in the "Add Widgets" panel) afterwards. I've never done anything like this before and I'm new to Linux so I've probably done something wrong. I suspect that since I've git-cloned your repository to my 'Home' directory that even though it says the installation was successful that it doesn't matter because widgets should go somewhere else directory-wise; could that be the case? Thanks in advance!

**Comment by psifidotos** [comment]
this is no help forum, you need to ask at your distro forums
