### ISSUE TITLE
Can't install from "Get New Widgets.."

### ISSUE THREAD

**Issue by Deliphin** [psifidotos/applet-window-appmenu#198]
Attempting to install 0.7.1 from the get new widgets tool, and I get the following error. I've tried multiple times, and I've tried after a reboot. I also tried in a VM. Additionally, this is over the course of several days where I successfully installed several other widgets, so it's extremely unlikely that store.kde.org is to blame.

![image](https://user-images.githubusercontent.com/14265753/158752218-bdf8d3d7-0698-42b1-a877-9fb7b1d0a1d4.png)

**Comment by psifidotos** [comment]
of course you can not, the appmenu applet needs to be rebuilt in your system. Only alternative is to rely on your distro packages to provide it for you.
