### ISSUE TITLE
Unable to hover over submenu bigger than the width of main menu.

### ISSUE THREAD

**Issue by KraiiFox** [psifidotos/applet-window-appmenu#199]
I think I have the same issue as #194  but updates didn't seem to have fixed it for me. I have been using latte dock in combination with appmenu applet for quite a while now and everything was working fine until a couple of weeks to a month ago.

When hovering over submenu that's bigger than the main menu, it loses focus and selects the next menu instead. 
I am on EndeavourOS (Arch based). Everything is up to date with latte dock version 0.10.76 and appmenu version 0.7.1

![Screenshot_20220319_010154](https://user-images.githubusercontent.com/43300558/159049055-195a14a5-1246-46e6-b91d-e16c31663f79.png)
![Screenshot_20220319_005805](https://user-images.githubusercontent.com/43300558/159049060-50d2184c-7d4f-4bce-b61b-63c14f33b1b4.png)

[test](https://user-images.githubusercontent.com/43300558/159050243-bf346838-c8ae-48c1-88c9-278410e9f567.mp4)

During a recording, I noticed it stops bugging out after a certain number of submenus:

https://user-images.githubusercontent.com/43300558/159051836-88acbf59-d6a6-4733-b33c-205e3f42256a.mp4

I'll be happy to help out if you need any more info or logs :)

**Comment by psifidotos** [comment]
have you tried master version?

**Comment by psifidotos** [comment]
this is not reproducable in my system

1. is this on wayland?
2. send your latte layout to check it out in my system

**Comment by psifidotos** [comment]
Ah, you are using Kvantum... switch to Breeze application style, is it reproducable?

**Comment by KraiiFox** [comment]
Oh goddammit, it randomly fixed itself after all these time. What an unfortunate time.

Nevertheless I'll answer your questions if it's anything useful :)

> this is not reproducable in my system
> 
>     1. is this on wayland?
> 
>     2. send your latte layout to check it out in my system

1. It's on x11
2. [Here you go](https://github.com/psifidotos/applet-window-appmenu/files/8310029/github.latte.zip)



> Ah, you are using Kvantum... switch to Breeze application style, is it reproducable?

I'm using the [lightly theme](https://github.com/Luwx/Lightly) which is based on Breeze

**Comment by psifidotos** [comment]
Do you have this issue with Breeze application style?

**Comment by Mameng57** [comment]
Confirm the culprit  was Latte dock itself

![image](https://user-images.githubusercontent.com/59303767/159716384-5cf1614a-5e33-4c70-be40-005eea83dfd4.png)
set Zoom on Hover to 0 fix this issue
