### ISSUE TITLE
Maximum Length is buggy

### ISSUE THREAD

**Issue by marhkb** [psifidotos/applet-window-appmenu#2]
I can not set arbitrary values (e.g. 999 pixels) and when I set 200 pixels I got some weird results for different windows
![app1](https://user-images.githubusercontent.com/3630213/48660087-5a704c80-ea5c-11e8-9eeb-ed0722dd9f72.png)
![app2](https://user-images.githubusercontent.com/3630213/48660088-5a704c80-ea5c-11e8-9c19-e5f6225b6267.png)
![app3](https://user-images.githubusercontent.com/3630213/48660089-5a704c80-ea5c-11e8-95d4-dbe1d6f09ffc.png)

**Comment by psifidotos** [comment]
this is not related to AppMenu open this issue at Window Title....
