### ISSUE TITLE
Konsole doesn't show menu

### ISSUE THREAD

**Issue by rplanchuelo** [psifidotos/applet-window-appmenu#20]
neither Kontact

**Comment by psifidotos** [comment]
1. Some me screenshot
2. Does it show in plasma global menu?

**Comment by psifidotos** [comment]
actually both Konsole and Kontact show menus in my system, what panel are you using?

**Comment by psifidotos** [comment]
can not confirm this... both they work ok with plasma panels and Latte panels

**Comment by rplanchuelo** [comment]
I've just installed from AUR the three apps (plasma5-applets-window-appmenu plasma5-applets-window-buttons plasma5-applets-window-title) and they work right for me.

Thanks a lot. Great job

**Comment by alex1701c** [comment]
I have this issue and am running KDE Neon developer edition(beta version) and it does not show the menu items for Konsole.

I have the latest version from github using the install script installed.  
![konsole_menu_bug](https://user-images.githubusercontent.com/38406607/75100457-eb25c880-55cd-11ea-991e-166ddda8fa24.png)

But it works fine for example  with Firefox and Kate.
And I am using a normal panel.

Thanks an advance 😄.
