### ISSUE TITLE
[feature] Customize font size and bold

### ISSUE THREAD

**Issue by bluee111** [psifidotos/applet-window-appmenu#202]
Hello friends, first of all thank you for this splendid extension, it is of excellent utility.
I do not know if it is possible to add a feature to customize the font size without affecting my entire system, I think this would be perfect, please, would you be so kind to add this feature?
I have seen this other widget "Better inline clock" that has this feature, something similar to it would be very good.
The date and time on the right is "Better inline clock" 
https://i.ibb.co/6v9SKvg/Screenshot-20220501-212502.png

"Better inline clock"
https://www.pling.com/p/1245902

I know you can change the size from System Preferences >font , but this affects the whole system like Dolphin and file/folder names :(

**Comment by psifidotos** [comment]
sorry, too messy to add...
