### ISSUE TITLE
[wayland] appmenu unresponsive when hovering over other options after clicking on one

### ISSUE THREAD

**Issue by ryu-ketsueki** [psifidotos/applet-window-appmenu#204]
This is a bit tricky to explain what exactly is happening so I recorded the bug in question. Can't work around it unless I close the application or restart latte entirely. This is on Wayland. 

https://user-images.githubusercontent.com/39316730/168334391-2499fdb6-4517-4869-b61b-5ed7efc47bd2.mp4

**Comment by andrevmatos** [comment]
I can confirm this happening on Plasma 5.24.5 on NixOS on Wayland as well: clicking on a menu shows it, but then moving the mouse to any other menu makes the applet becomes unresponsive besides the hovering effect (but no other nor first menu is shown). It's quite hard to make it react again, usually involving finding another app, act on its menu, and then go back to first app.

**Comment by artfox3** [comment]
Same happening with Plasma 5.24.5 using wayland on arch linux

**Comment by psifidotos** [comment]
known issue... I believe plasma global menu applet has the same issue... I think it is a Qt5 issue

**Comment by andrevmatos** [comment]
Plasma global applet doesn't have this issue. I actually had to switch to it (with a small patch to show menus from windows from all screens, since it doesn't expose this option), but it's working fine, even the new Search menu
