### ISSUE TITLE
[readme] - add features that do not exist in the main plasma global menu

### ISSUE THREAD

**Issue by D3SOX** [psifidotos/applet-window-appmenu#205]
I'm not sure if I should use this or the stock Global Menu applet.
Can you add some informational text to the README explaining the differences and why someone should use one or the other?

**Comment by D3SOX** [comment]
No response?

**Comment by D3SOX** [comment]
I don't want to annoy you but could you at least provide any answer to this?

**Comment by psifidotos** [comment]
I do not want to add a comparison in the README, comparison usually have a negative sense. On the other hand adding the extra features that someone gets with AppMenu makes sense.

**Comment by psifidotos** [comment]
readme updated
