### ISSUE TITLE
LibTaskManager not found in Opensuse Tumbleweed

### ISSUE THREAD

**Issue by ChrTall** [psifidotos/applet-window-appmenu#206]
I can not build from source, because LibTaskManager is not found on Opensuse Tumbleweed.
I think the required dependencies for opensuse in the README are outdated.

**Comment by bluee111** [comment]
I am on Opensuse Leap 5.4 and I also had that error about `LibTaskManager` and installing `kitemmodels-devel` solved the issue. It may or may not be the right one, but it solved it.
Just in case I leave all the dependencies that I use
`sudo zypper install cmake extra-cmake-modules libxcb-devel plasma5-workspace-devel kwindowsystem-devel plasma-framework-devel libdbusmenu-gtk2-devel libdbusmenu-gtk3-devel ksysguard5 kitemmodels-devel`

**Comment by psifidotos** [comment]
libtaskmanager is part of plasma workspace
