### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by PQCraft** [psifidotos/applet-window-appmenu#210]
I am on plasma 5.25.3 and the menu still shows up on the application despite me adding this to my bar. The default global menu is also broken now (it wasn't before) and I will be making a bug report about that too.

**Comment by PQCraft** [comment]
Solved with some local trolling

**Comment by Vistaus** [comment]
> Solved with some local trolling

What local trolling? I would love to make this work on Wayland.

**Comment by PQCraft** [comment]
@Vistaus I somehow disabled the "Application menus daemon" background service. Enabling that service again made it work.

**Comment by KennFatt** [comment]
this should be in the documentation too
