### ISSUE TITLE
Clicking on "File" of Libreoffice Calc does not expand the menu

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-appmenu#26]
Other buttons work correctly, but "File" doesn't.
On the official Plasma's Global menu, click on "File" make Latte crash.

![libreoffice_file](https://user-images.githubusercontent.com/11857205/49203347-82579c80-f3da-11e8-9908-03bdf65a1dcf.gif)

**Comment by psifidotos** [comment]
If you try plasma global menu into a plasma panel you will notice the exact same issue, so this is upstream. Only way I have found to fix it is to open a second window of the same app. Try to open a second new Libre office Calc window and afterwards menus for both windows are working ok

**Comment by trmdi** [comment]
From another bug report, you could fix it by changing the focus to another window then go back to the LibreOffice window. Do you have any workaround from this?
