### ISSUE TITLE
Unable to install on Plasma 5.14.4 

### ISSUE THREAD

**Issue by suricactus** [psifidotos/applet-window-appmenu#30]
It worked perfectly on 5.12, however, after I updated to 5.14 it does not show as a widget when I install it. I compiled it manually and attached it to my Latte panel, but then the menu does not appear, even though I've enabled it in the setting. A workaround is to use Title and Button applets separately. However, this does not cover 100% of the functionality of the Appmenu applet.

**Comment by psifidotos** [comment]
This is not Active Window Control. Window AppMenu doe not provide title and buttons
