### ISSUE TITLE
[Feature Request] Idea/request to recreate AWC/Unity global menu behavior

### ISSUE THREAD

**Issue by ChrisP4** [psifidotos/applet-window-appmenu#32]
Hi :)

What do you think about AWC/Unity's behavior of merging the program's title with its menu where the title is shown by default and when you mouse over it shows the menu instead?

It's one of the thing I've loved with Unity, do you think this could be done? Perhaps as a merge of the appmenu and title widgets?

**Comment by psifidotos** [comment]
this would break totally the idea of having three applets to do the job.

Only way I could think of that could be done is by using Latte to do this...

Latte could provide a way for applets to communicate between them. And that communication could be totally on applets responsibility what to do with it....

For example the Windows AppMenu could be always hidden and it could rely on Windows Title to appear. When the Windows AppMenu becomes hidden then it could inform the Window Title to show itself etc.etc...

That way no major new code would be needed for both applets and at the same time the user could keep all the options that are provided for each applet...

**Comment by moffis** [comment]
I am interested in this, too.
I wonder whether it is possible to create an applet that can contain other applets?
Then based on rules (MouseOver, etc.) one is visible and the other is hidden.

**Comment by psifidotos** [comment]
Systray is such an applet that contains other applets but unfortunately it is too complicated in my opinion to implement one. Zren was having an idea to support such an applet instead of AWC and use my three Window applets in that applet. But I haven't heard anything more.

**Comment by psifidotos** [comment]
is that what we are talking about?

![windowtitle_appmenu](https://user-images.githubusercontent.com/2216474/53519865-efafc200-3adc-11e9-8b1e-6f5c14db2577.gif)

![image](https://user-images.githubusercontent.com/2216474/53519924-1241db00-3add-11e9-885e-95ee307b5360.png)
