### ISSUE TITLE
suggestion for adding resources.

### ISSUE THREAD

**Issue by jcmljunior** [psifidotos/applet-window-appmenu#34]
Inglês
Would it be possible to implement a function where instead of hiding the menu when the user is on your desktop? I wish I had some sort of quick access to places.
It would basically look pretty similar to OS X.
Thanks

Português
Seria possível implementar uma função onde ao invés de ocultar o menu quando o usuário esta em sua área de trabalho? gostaria que tivesse uma especie de acesso rápido aos locais.
Seria basicamente bem semelhante ao OS X.
Obrigado

Demonstração/Demo:
![demo](https://user-images.githubusercontent.com/35886100/50387458-e7ee2e80-06e3-11e9-9b3b-1a59cdab2b20.jpg)

**Comment by jcmljunior** [comment]
please do not remove the default mode, just add an alternative method where the user chooses the way the menu will behave.
if you find an interesting resource.

**Comment by psifidotos** [comment]
I can not understand what you propose

**Comment by jcmljunior** [comment]
I would like a new feature on the menu.
Currently when we are in the desktop, the menu is hidden.
The suggestion itself is the addition of local access.

Files >> Documents >> Musics >> Picture >> Video

Sorry for the language, I do not speak English.
Do you understand this time?

**Comment by jcmljunior** [comment]
before:
![screenshot_20181224_015515](https://user-images.githubusercontent.com/35886100/50390626-85ffea00-0720-11e9-8ede-be554558f9bc.png)

after:
![design](https://user-images.githubusercontent.com/35886100/50390618-6072e080-0720-11e9-95df-4d8f81afa40f.jpeg)

**Comment by psifidotos** [comment]
Sorry this is out of scope for this plasmoid
