### ISSUE TITLE
[Feature request] Option to change the spacing between menus elements

### ISSUE THREAD

**Issue by ahmed-h-ayyad** [psifidotos/applet-window-appmenu#35]
I think the default space between menu items is too wide so please  add an option to increase/decrease it or just decrease the default spacing

![screenshot_20190103_141855](https://user-images.githubusercontent.com/37955014/50637393-8ee38d80-0f62-11e9-889a-b7f62a3557d7.png)

**Comment by ahmed-h-ayyad** [comment]
so?

**Comment by kupiqu** [comment]
So nothing, just giving some information, which at least helps to reformulate the title of the issue, from spacing between menu items, to within menu items label margins.

Other than that @psifidotos will say...

**Comment by psifidotos** [comment]
> Other than that @psifidotos will say...

I will think about it, I am currently working endlessly the applet's Latte support for fillWidth(s)/Height(s) applets. I am trying to have Latte panels that look almost identical to plasma panels. Hard stuff but in the end I wont have to implement applets and make sure that they behave and look the same both for Latte panels and Plasma panels.

It is very hard to make it happen but I think that I am reaching there...

**Comment by psifidotos** [comment]
fixed with: https://github.com/psifidotos/applet-window-appmenu/commit/ba64b390c235b1b6de2f1df77df7a4880ec1eb6e
