### ISSUE TITLE
Changing to empty desktops twice makes last menu reappear

### ISSUE THREAD

**Issue by r3b311i0n** [psifidotos/applet-window-appmenu#36]
Opening an application and then moving to two empty desktops consecutively makes the previous menu reappear.

![desktop1](https://user-images.githubusercontent.com/10097295/50735621-361d2a80-11d8-11e9-9352-080673aa7167.jpg)

![desktop2](https://user-images.githubusercontent.com/10097295/50735645-65339c00-11d8-11e9-8f1c-c10d1bda534f.jpg)

![desktop3](https://user-images.githubusercontent.com/10097295/50735653-6d8bd700-11d8-11e9-98b4-e4067e0b617a.jpg)

env:

```
Plasma: 5.14.4
Latte: 0.8.4
applet-window-appmenu: latest-master
```

**Comment by psifidotos** [comment]
how did you hide the appmenu in the second screenshot?

**Comment by r3b311i0n** [comment]
@psifidotos using `Show only menus from active applications`

**Comment by kupiqu** [comment]
> @psifidotos using `Show only menus from active applications`

Yes, me too

> Moving from the original desktop to the first empty desktop will show the activity name (in my case) or just nothing (in OP case) depending on settings.

Oops, I somehow got confused focusing on the behavior of the title applet before

**Comment by psifidotos** [comment]
I cant replicate that, big chance 0.8.5 will fix it...

@kupiqu @r3b311i0n 
can you check if this can be reproduced with a plasma panel and Window AppMenu applet?

**Comment by psifidotos** [comment]
Oh... I reproduced...

**Comment by r3b311i0n** [comment]
It doesn't seem to happen with a Plasma Panel...

**Comment by psifidotos** [comment]
if you enable "filter by active" after that commit it should work ok
