### ISSUE TITLE
Do not show appmenu on wayland

### ISSUE THREAD

**Issue by CossonLeo** [psifidotos/applet-window-appmenu#37]
Do not show appmenu on wayland

**Comment by trmdi** [comment]
Related bug: https://bugs.kde.org/show_bug.cgi?id=385880

**Comment by psifidotos** [comment]
@Cosson2017 have you tried with version 0.3 if this still exists as an issue?

**Comment by Cosson2017** [comment]
still not work

**Comment by psifidotos** [comment]
probably needs to be solved upstream first
