### ISSUE TITLE
Too little space for whole menu - what should it do?

### ISSUE THREAD

**Issue by ChrisP4** [psifidotos/applet-window-appmenu#38]
I'm not sure if this is the correct place for saying this. Or if there's already a way things are supposed to work and I haven't figured it out.

I'm using this applet as well as the title one (on a latte panel) and it sometimes happens that my laptop screen is too small to show both the window's title and the full window's menu. So this is how it looks:

![screenshot_example_appletwindowmenu](https://user-images.githubusercontent.com/14283056/51276962-e3651f00-19de-11e9-9851-07723d7b6548.png)

It clearly shows that there's more menu entries but I'm unsure as to what is supposed to happen. Should it slide somehow so I can reach all the options? Is this an issue for how the latte panel should treat shortage of space for the applets?

Thanks for everything!!!

**Comment by psifidotos** [comment]
> It clearly shows that there's more menu entries but I'm unsure as to what is supposed to happen. Should it slide somehow so I can reach all the options?

yes, you should be able to use the mouse scroll wheel in order to move the menu items around...

> Is this an issue for how the latte panel should treat shortage of space for the applets?

no, this mechanism is totally on applet responsibility

**Comment by trmdi** [comment]
The window title is too long. Why don't you replace it with "GIMP" ?

**Comment by ChrisP4** [comment]
@trmdi yes this would solve this particular example but it was broader than this.

@psifidotos Thanks! I had moved with the arrow keys and tried to scroll but I had tried to scroll down not up. To me it seems a bit counter-intuitive but it is horizontal so what do I know.

Thanks!!
