### ISSUE TITLE
No target specified error & no makefile found

### ISSUE THREAD

**Issue by YamiYukiSenpai** [psifidotos/applet-window-appmenu#39]
[CMakeOutput.log](https://github.com/psifidotos/applet-window-appmenu/files/2792366/CMakeOutput.log)
I attached the log.  Hope that helps.

I downloaded the latest tarball from the release section and cloned the repo, both end up with the same error.

**Comment by psifidotos** [comment]
Something is missing from your system, best way is to ask for help from your distro packagers or users
