### ISSUE TITLE
When users press Alt, the appmenu displays "&" instead of "_"

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-appmenu#4]
![image](https://user-images.githubusercontent.com/11857205/48662399-39d3e100-eab4-11e8-9e35-39839fb53cf2.png)

**Comment by trmdi** [comment]
Btw, if you place Application menu on the titlebar (Alt+F2 > Window Decorations >Buttons) when you press a hotkey with Alt, both of them are triggered. How will you handle this?
![image](https://user-images.githubusercontent.com/11857205/48662494-53c1f380-eab5-11e8-8def-2bc38da06180.png)

**Comment by kupiqu** [comment]
> Btw, if you place Application menu on the titlebar (Alt+F2 > Window Decorations >Buttons) when you press a hotkey with Alt, both of them are triggered. How will you handle this?

I filled a bug against plasma's global menu exactly about this: https://bugs.kde.org/show_bug.cgi?id=397912

If @psifidotos can fix it, it could also apply to plasma's global menu...

**Comment by psifidotos** [comment]
> both of them are triggered. How will you handle this?

I wont handle this... and there is no way for an applet to handle this...

**Comment by trmdi** [comment]
> > both of them are triggered. How will you handle this?
> 
> I wont handle this... and there is no way for an applet to handle this...

Where should I report this bug to ?

**Comment by psifidotos** [comment]
there is this bug correct?
> https://bugs.kde.org/show_bug.cgi?id=397912

only thing the applet could do is to disable the actions triggering for its menus if the user wants to...
and I am not pretty certain about it...
either way you should open a different thread for this... For the kwin part I have no idea...

**Comment by kupiqu** [comment]
It seems that buttons size gets increase by pressing Alt, when `_` appears. I don't recall this happening in plasma's global menu.

Should I fill a different issue?

**Comment by psifidotos** [comment]
> Should I fill a different issue?

definitely... and I can reproduce in my system so you must demonstrate it also...

**Comment by psifidotos** [comment]
I can not reproduce *
