### ISSUE TITLE
Plasmashell keeps crashing when I try to use the menu

### ISSUE THREAD

**Issue by YamiYukiSenpai** [psifidotos/applet-window-appmenu#40]
```
[ 2078.601576] plasmashell[31644]: segfault at 0 ip 00007fe3a4e18c4e sp 00007fff4ef9ea30 error 4 in plasma_applet_windowappmenu.so[7fe3a4e18000+4000]
[ 2078.601581] Code: 45 88 48 89 c7 e8 7c fd ff ff 85 c0 0f 94 c0 84 c0 0f 84 a8 00 00 00 48 8b 45 88 48 83 c0 40 48 89 c7 e8 31 1b 00 00 48 89 c3 <48> 8b 03 48 83 c0 60 4c 8b 20 48 8d 45 d0 48 89 c7 e8 96 16 00 00 
[ 2107.154826] plasmashell[31851]: segfault at 0 ip 00007f3817fe3c4e sp 00007fffa10ea640 error 4 in plasma_applet_windowappmenu.so[7f3817fe3000+4000]
[ 2107.154831] Code: 45 88 48 89 c7 e8 7c fd ff ff 85 c0 0f 94 c0 84 c0 0f 84 a8 00 00 00 48 8b 45 88 48 83 c0 40 48 89 c7 e8 31 1b 00 00 48 89 c3 <48> 8b 03 48 83 c0 60 4c 8b 20 48 8d 45 d0 48 89 c7 e8 96 16 00 00 
[ 2139.073968] plasmashell[32088]: segfault at 0 ip 00007f478c01ac4e sp 00007ffe5b4005b0 error 4 in plasma_applet_windowappmenu.so[7f478c01a000+4000]
[ 2139.073973] Code: 45 88 48 89 c7 e8 7c fd ff ff 85 c0 0f 94 c0 84 c0 0f 84 a8 00 00 00 48 8b 45 88 48 83 c0 40 48 89 c7 e8 31 1b 00 00 48 89 c3 <48> 8b 03 48 83 c0 60 4c 8b 20 48 8d 45 d0 48 89 c7 e8 96 16 00 00 
```

**Comment by psifidotos** [comment]
1. How did you install the applet?
2. Did you update plasma lately?

**Comment by psifidotos** [comment]
3. What is the crash report from kcrash?

**Comment by YamiYukiSenpai** [comment]
1) I downloaded v0.2 from the release page.
2) No.  I'm currently on Plasma 5.14.5 on Kubuntu 18.10 (installed via backports).
3) [plasmashell-20190125-104027.kcrash.txt](https://github.com/psifidotos/applet-window-appmenu/files/2796764/plasmashell-20190125-104027.kcrash.txt)

**Comment by psifidotos** [comment]
>     1. I downloaded v0.2 from the release page.
> 

can you try master(git) version in order to check if it crashes again for you and if it is the same crash?

**Comment by psifidotos** [comment]
no info

**Comment by YamiYukiSenpai** [comment]
Sorry. I've been busy.  Class was just cancelled today.  I know you said to use the one from master, but this is from v0.3 (just installed on my laptop (which has Latte installed) & my desktop, which uses Plasma's panels).  BTW, this [kcrash](https://github.com/psifidotos/applet-window-appmenu/files/2837126/plasmashell-20190206-105747.kcrash.txt)) is from my desktop.  Laptop's working fine.
