### ISSUE TITLE
Appmenu sometimes occupies space even on desktop

### ISSUE THREAD

**Issue by azazello4** [psifidotos/applet-window-appmenu#41]
[Kubuntu 18.10, Appmenu from git] Sometimes when switching to an empty desktop/minimizing all the windows in a desktop (it seems to be reproducible after opening System Settings) the applet gets expanded even if it is not showing any menu.

![centered](https://user-images.githubusercontent.com/23563628/52223044-265f3780-28a5-11e9-87c4-7d41df5fb07b.png)
![not centered](https://user-images.githubusercontent.com/23563628/52223047-2828fb00-28a5-11e9-9413-f45de72d787b.png)

**Comment by psifidotos** [comment]
Give me a screenshot of Latte in Edit Mode

**Comment by azazello4** [comment]
![image](https://user-images.githubusercontent.com/23563628/52223725-8acec680-28a6-11e9-8beb-1aba51d994cf.png)

**Comment by psifidotos** [comment]
strange setup... you want your app menu in the center?

**Comment by azazello4** [comment]
Yeah that's the idea. I can set the alignment to left though, don't want to cause any headache.
