### ISSUE TITLE
LibreOffice - Duplicate Menu Listings showing up

### ISSUE THREAD

**Issue by RavenTheDev** [psifidotos/applet-window-appmenu#42]
When using LibreOffice, the "File, Edit" etc Menus show up twice. Please see the screenshot. I can confirm this is not a case of having 2x widgets on the panel.

![screenshot_20190212_215037](https://user-images.githubusercontent.com/11475987/52640123-bab64380-2f10-11e9-962d-5a841f0bd12e.png)

**Comment by trmdi** [comment]
https://bugs.kde.org/show_bug.cgi?id=402044

**Comment by psifidotos** [comment]
fixed upstream
