### ISSUE TITLE
Allow dragging on the appmenu area to move windows

### ISSUE THREAD

**Issue by ripefig** [psifidotos/applet-window-appmenu#43]
The appmenu takes up a lot of space and it would be useful to use that area to move windows (like the empty space). I know the sytem default is press to activate menu on mouse down, however this isn't the default for other plasma menus.

So I would propose activating the menubar on mouse release. Mouse down and drag would move the window.

It would be logical here to do the same thing for your other applets, including window title and window buttons. Dragging on these applets right now performs no useful function.

Maybe even do this for the dock, but you'd have to have a separate lock setting for it so I am not sure it's worth your effort.

**Comment by psifidotos** [comment]
Yeah ok, can you provide a patch for this?
