### ISSUE TITLE
Add suport for sliding menu

### ISSUE THREAD

**Issue by gmsanchez** [psifidotos/applet-window-appmenu#45]
When displaying a menu that has a lot of elements, the applet should let the user choose to slide the menu (adding arrows on the top and bottom) or display as it does now (in my case, it uses the full screen to render Firefox's bookmarks):

![screenshot_20190227_000837](https://user-images.githubusercontent.com/2853668/53463189-01ce2980-3a25-11e9-841a-f9d7cb24421a.png)

**Comment by psifidotos** [comment]
This is not applet responsibility but Qt responsibility

**Comment by gmsanchez** [comment]
Thanks for the respone. I filled a bug report in KDE bug tracking system to see if this issue can be addressed: https://bugs.kde.org/show_bug.cgi?id=404942

**Comment by psifidotos** [comment]
perfect... Nate already sent a patch
