### ISSUE TITLE
It's cropped

### ISSUE THREAD

**Issue by sira313** [psifidotos/applet-window-appmenu#46]
I use default settings but it's cropped just like this
![cropped](https://i.ibb.co/qrbsqTY/Screenshot-20190228-032232.png)

**Comment by psifidotos** [comment]
have you add a panel spacer after the appmenu?

**Comment by sira313** [comment]
> have you add a panel spacer after the appmenu?

yes i add that to make the systray stay on the right side

**Comment by psifidotos** [comment]
> yes i add that to make the systray stay on the right side

you dont have to, remove it and enable in appmenu settings: **Always use maximum available width**
