### ISSUE TITLE
Doesn't show libreoffice menu

### ISSUE THREAD

**Issue by vk001716** [psifidotos/applet-window-appmenu#48]
It dosen't show the librreoffice menu on ubuntu 18.0.4
I had previously installed the arch linux where it worked fine.
I installed it by using

`sudo apt install libreoffice-kde`

Let me know if I haven't installed any dependency.
![screenshot_20190307_052512](https://user-images.githubusercontent.com/36535270/53922430-4481a880-409a-11e9-8c8d-5bd02ddcad25.png)

**Comment by psifidotos** [comment]
this is not related to this applet, you will have the same issue with all appmenu(s) in plasma ...

**Comment by psifidotos** [comment]
please search the internet how to accomplish this in a plasma environment
