### ISSUE TITLE
Window title slides off towards the bottom of the panel.

### ISSUE THREAD

**Issue by ripefig** [psifidotos/applet-window-appmenu#49]
![image](https://user-images.githubusercontent.com/45201036/53993353-37b79000-4140-11e9-8a26-94f459aff83b.png)

I have it set to centered on the panel, not sure if it matters. If you clear the widget (i.e by clicking on the desktop so that the widget goes blank), it jumps back to normal position. Then after you switch to another window, it jumps back down. 

This only happens on certain windows - I can't spot any pattern to it.

**Comment by psifidotos** [comment]
Give more details, I can't understand what you are describing..

How can I reproduce?

**Comment by ripefig** [comment]
Wrong place - this was for the WM title.

In my case I just have the following settings and the WM title applet is set in the center of the panel. Chromium seem to be the main offender, but other programs can do this as well. Just be on the lookout for it - if you can't reproduce it don't bother.

![image](https://user-images.githubusercontent.com/45201036/54030821-df26d800-41bd-11e9-9658-4d80657c2dc5.png)


Offset bug:
![image](https://user-images.githubusercontent.com/45201036/54030726-8bb48a00-41bd-11e9-97dd-3430989da640.png)

Normal behavior:
![image](https://user-images.githubusercontent.com/45201036/54030803-d1715280-41bd-11e9-92a7-0d2bc5c6647b.png)

**Comment by psifidotos** [comment]
> and the WM title applet is set in the center of the panel. 

what do you mean? Plasma panel or Latte panel?

**Comment by ripefig** [comment]
Latte. Never tried plasma

**Comment by psifidotos** [comment]
1. is this still valid with latest commits?
2. Are you using Latte stable OR master?
2. Provide please screenshots that show your entire Latte panel

**Comment by ripefig** [comment]
![image](https://user-images.githubusercontent.com/45201036/55293756-80dac700-5402-11e9-8800-2c07ede153d8.png)

**Comment by psifidotos** [comment]
Open a new issue at the appropriate place and give all the details needed to reproduce this

**Comment by ripefig** [comment]
https://github.com/psifidotos/applet-window-title/issues/50
