### ISSUE TITLE
Graphical inconsistencies with the plasma menubar

### ISSUE THREAD

**Issue by gondsman** [psifidotos/applet-window-appmenu#5]
There are two small issues with the looks of this applet.
First of all, when pressing ALT to highlight the letter shortcut to open the menu with the keyboard, instead of being underlined the letter is preceded by an '&' sign. It still works, but it's not very clear.
Second, the menubar has colored highlights when hovering or selecting a menu, instead of a shadow-like highlight (although this might be related to the plasma theme). It is perfectly ok for me and the applet looks just fine (probably better than the original one), but I wanted to report it as you wrote it was mostly based on the official plasma menubar applet, so I was surprised it looked different.

**Comment by psifidotos** [comment]
Can you provide some screenshots for the colors comparison?

**Comment by psifidotos** [comment]
ok some info for this... plasma applet uses PlasmaComponents.ToolButton which is using the svg files from plasma theme to draw itself... unfortunately this isnt possible with new Latte... Latte is offering a color palette to be respected from applets so in the end that is what can be done for now...

**Comment by psifidotos** [comment]
> I dind't visualize any change after the commit, is this expected?

retry with latest master even though I am not that sure that I will keep it...
it depends from new Latte coloring mechanism....

**Comment by kupiqu** [comment]
Not much of a difference. If I don't recall wrong in plasma only the stroke was apparent on hovering. I guess there's not much we can do.

**Comment by psifidotos** [comment]
> Not much of a difference

on hovering has a different color than when then showing a menu... If you are using Latte you must check this with latest git version of Latte

**Comment by kupiqu** [comment]
I can see a small difference between the two in Latte 0.8.2

**Comment by psifidotos** [comment]
I have just added a little shadow to the buttons ... Latte v0.8.x does not support the new Latte painting so what you see is how it looks in plasma panel...

**Comment by kupiqu** [comment]
are you releasing latte's new version soon? it's so stable and works so good that I stopped building from master long time ago... :)

**Comment by psifidotos** [comment]
> are you releasing latte's new version soon? it's so stable and works so good that I stopped building from master long time ago... :)

nope... :) Latte releases a new stable version once per year... I am the only one maintaining and adding features... so next stable is scheduled for Summer 2019 as long as there are no critical issues introduced...

**Comment by kupiqu** [comment]
> nope... :) Latte releases a new stable version once per year... I am the only one maintaining and adding features... so next stable is scheduled for Summer 2019 as long as there are no critical issues introduced...

Once a year seems like a long time (plasma releases every 4 months I think), but it's fine I'll wait for it... :)
