### ISSUE TITLE
Eyecandy: App icon styling like old Gnome shell

### ISSUE THREAD

**Issue by ripefig** [psifidotos/applet-window-appmenu#50]
Most icons don't look good at low res, since under KDE you aren't going to be using symbolic icons in the panel widget. 

![image](https://user-images.githubusercontent.com/45201036/53993750-4783a400-4141-11e9-801d-93048ddf297b.png)

It would me much more visually appealing if appmenu adopted the old Gnome model, which enlarges the app icon:

![image](https://user-images.githubusercontent.com/45201036/53993694-2d49c600-4141-11e9-9874-4e12f9bfd53b.png)

Another example:

![image](https://user-images.githubusercontent.com/45201036/53994113-69315b00-4142-11e9-9c65-04c3acb748fd.png)

I think this is much more visually appealing, and it doesn't require any special icons.

This could be integrated into the of appmenu widget (and maybe all other widgets as well, to make it more flexible for users. It would essentially be an overlay that is positioned at distance from the widget in question. The distance is set by the user.)

**Comment by psifidotos** [comment]
Why don't you use Window Title applet for this?

**Comment by ripefig** [comment]
Cause then you can't get the effect of it fading into the menubar, lol.

 It would make sense to have the icon option in all three widgets, IMO (buttons, title and menu).

**Comment by psifidotos** [comment]
sorry I am not interested... providing three different applets and not reuse code between them is a design decision...
