### ISSUE TITLE
Any way to make the icons the menus scale properly?

### ISSUE THREAD

**Issue by ripefig** [psifidotos/applet-window-appmenu#51]
I am using X11. The icons in the menus stay the same size after scaling the interface.

**Comment by psifidotos** [comment]
Does this work with plasma global menu?

**Comment by ripefig** [comment]
My guess would be no.

**Comment by psifidotos** [comment]
so that is Qt responsibility and not per applet one...

feel free to open a bug report to plasma devs for Global menu also and see how it goes...

reference here the plasma bug report in order for me to follow it in case I am wrong and something can be done from applet side
