### ISSUE TITLE
Add a option to scroll horizontally instead of vertically on appmenu

### ISSUE THREAD

**Issue by codelalala** [psifidotos/applet-window-appmenu#52]
In my laptop, it seems like I can't get the menu to scroll. My setup is Manjaro KDE with libinput driver. I put the widget on latte dock on panel mode. Below is a picture of my latte dock setup
![image](https://user-images.githubusercontent.com/1414575/54095149-10e59d80-437c-11e9-8a68-9799dad23102.png)
Your tools are the must haves on laptop. Please give my any advise to fix it. Thank you very much.

**Comment by psifidotos** [comment]
show me please screenshots from plasma systemsettings->libinput settings...

**Comment by codelalala** [comment]
Can you be more specific about which "plasma systemsettings->libinput settings" are you refer to?
This is the touchpad setting page:
![image](https://user-images.githubusercontent.com/1414575/54152332-61f4a080-4413-11e9-98fa-53cb2ee85486.png)

**Comment by psifidotos** [comment]
These settings are like in my system

1. How do you check if Synaptics or libinput is used in your system?
2. If you try to scroll a little roughly it doesn't work?
3. Have you tried Latte, scrolling features in Latte are also failing?

**Comment by codelalala** [comment]
1. I am using Manjaro KDE, I can only choose synaptics or libinput. If I use Synaptics it will install on top of libinput and disables libinput. I am using libinput with libinput gestures with no Synaptics installation.
2. Just tried roughly scroll and it does not work. I also tried horizontal scroll in system and in firefox, and it works fine.
3. Can you tell me how to set up and try scrolling feature in Latte?

**Comment by psifidotos** [comment]
2. For the appmenu I think vertical scrolling is enabled for mouse and touchpads, I don't know about horizontal scrolling how it behaves
3. In Latte in Tasks tab there is an option to activate tasks through scrolling a task

**Comment by codelalala** [comment]
Thanks for your feedback. I though the appmenu should be horizontal scroll, and I just figure out that it is actually vertical scroll. I tried scroll vertically and it works. 
In this case, I think it is no longer a issue but rather a feature request. Do you think making it scroll horizontally is more reasonable due to its horizontal configuration? Is it hard to have a option for it?

**Comment by psifidotos** [comment]
I think I can add it... Please update also the issue title, I forget things easily

**Comment by psifidotos** [comment]
@codelalala can you please confirm the fix?

**Comment by codelalala** [comment]
@psifidotos I tried download the new source code and sh install.sh to override the existing widget, and it does not working. Did you implement horizontal scroll automatically or there is a option somewhere that I'll need to enable it?

Also, I can try to fully uninstall it first and reinstall. But can you teach me how to do that? I tried make uninstall but it still leaves the widget in widget menu.

**Comment by psifidotos** [comment]
> Did you implement horizontal scroll automatically

it should work directly both for vertical and horizontal scrolling, no option...

**Comment by psifidotos** [comment]
found it...

you have to enable:
![image](https://user-images.githubusercontent.com/2216474/54476862-88974a80-480a-11e9-8b2c-9b71201dbda0.png)

**Comment by codelalala** [comment]
![image](https://user-images.githubusercontent.com/1414575/54476889-86b49380-47d8-11e9-8630-55877cc85596.png)
On my computer, due to libinput, it is automatically enabled. In fact I can't even disable it, it is managed by libinput.

**Comment by psifidotos** [comment]
no idea for any further...

**Comment by psifidotos** [comment]
but it looks disabled... you probably need to enable it somehow in libinput

**Comment by psifidotos** [comment]
@codelalala the testing area on the right can you scroll it both vertical and horizontal through your touchpad?

**Comment by codelalala** [comment]
@psifidotos Yes, it works, both on the test area or in firefox or other apps. Does horizontal scroll works on your side?

**Comment by codelalala** [comment]
@psifidotos I think it might be that I have not fully uninstall the widget. Can you provide me a detailed way to fully uninstall the widget? I'll try a clean install.

**Comment by psifidotos** [comment]
just remove the qml part by removing: /usr/share/plasma/plasmoids/org.kde.windowappmenu

**Comment by codelalala** [comment]
@psifidotos After several reboot and system updates the horizontal scroll works fine now. Thanks for your help!
