### ISSUE TITLE
Request: Middle click to toggle between full app menu and single button

### ISSUE THREAD

**Issue by AndydeCleyre** [psifidotos/applet-window-appmenu#54]
Sometimes it's nice to see the whole menu, sometimes it's a distraction. I propose providing a simpler path to toggle between viewing the full app menu or just the single button, and middle click would seem to work while not conflicting with any other behavior that I can think of.

**Comment by psifidotos** [comment]
sorry I dont like the idea, an alternative could be to use Window Title and Window AppMenu in Unity mode style. That means that app menu is hidden by default until you hover the Window Title applet.

**Comment by AndydeCleyre** [comment]
I am not using Window Title and don't wish to. So I am going to use a script and trigger it with a custom global keyboard shortcut. How can I force Latte to recheck its configuration? The equivalent of `qdbus org.kde.KWin /KWin reconfigure`?

```python
#!/usr/bin/env python3
import re
from itertools import chain

from plumbum import local
from plumbum.cmd import (
    kreadconfig5 as kread,
    kwriteconfig5 as kwrite,
    qdbus
)


FILE = local.path('~/.config/latte/My Layout.layout.latte')


def get_cfg_header():
    header = re.search(
        r'(\[Containments\][^\n]+)\n([^\n]+\n)*plugin=org\.kde\.windowappmenu',
        FILE.read()
    ).group(1)
    return header.strip('[]').split('][') + ['Configuration', 'General']


def is_compact(header=None):
    header = header or get_cfg_header()
    return kread(
        '--file', FILE,
        [*chain.from_iterable(('--group', part) for part in header)],
        '--key', 'compactView'
    ).strip() == 'true'


def toggle_compact(header=None):
    header = header or get_cfg_header()
    kwrite(
        '--file', FILE,
        [*chain.from_iterable(('--group', part) for part in header)],
        '--key', 'compactView',
        '--type', 'bool',
        'false' if is_compact(header) else 'true'
    )


if __name__ == '__main__':
    toggle_compact()
    # qdbus('org.kde.lattedock', '/Latte', 'reconfigure')  # something like this
```

**Comment by psifidotos** [comment]
there is no way to achieve this... reconfiguring would mean to unload and reload afterwards all layout properties...

**Comment by AndydeCleyre** [comment]
So I'll have to make my shortcut relaunch latte entirely each time to achieve this?

**Comment by psifidotos** [comment]
none I can think of

**Comment by AndydeCleyre** [comment]
OK I will read the code later and try to figure out how the applet refreshes when settings are changed via the GUI.
