### ISSUE TITLE
Can't find the widget after installation

### ISSUE THREAD

**Issue by inquisitiv3** [psifidotos/applet-window-appmenu#59]
# Problem

After installing the widget via the widget browser and rebooting the system I can't find it in the list of installed widgets.

# Expected behavior

After installing the widget via the widget browser and rebooting the system the widget should show up in the list. After that I should be able to add it to my Latte dock.

# Steps to reproduce

1. Right-click on the Latte dock so the menu shows up
2. Click on `Add Widgets...`
3. Click on `Get new widgets`
4. Click on `Download New Plasma Widgets`
5. Find _Window AppMenu Applet_ by e.g. searching..
6. Click on `Install`
7. Reboot the machine
8. Redo step 1-5
9. Check that the `Install` button has been replaced by an `Uninstall` button
10. Redo step 1-2
11. Try to find the widget _Window AppMenu Applet_ in the list. Can't find it there.

# Troubleshooting

## Part A

1. Uninstalled the widget from the widget browser and rebooted the system afterward.
2. Redid all steps from _Steps to reproduce_.

Problem persists.

## Part B

1. Removed the widget _Window Title Applet_ from the Latte dock
2. Uninstalled the widget from the widget browser and rebooted the system afterwards.
3. Check that it's uninstalled according to the widget browser.

The widget still shows up in the list of available widgets

4. Press on the uninstall button in the widget list and reboot the system.

The widget still shows up in the list.

Can the problem described in _Part B_ have a connection to this issue?

# System information

Software/hardware | Version/model
-- | --
Operating System | Fedora 29
KDE Plasma Version | 5.14.5
Qt Version | 5.11.3
KDE Frameworks Version | 5.55.0
Kernel Version | 5.0.9-200.fc29.x86_64
OS Type | 64-bit
Processors | 4 × Intel® Core™ i5-3320M CPU @ 2.60GHz
Memory | 15,5 GiB of RAM

**Comment by psifidotos** [comment]
This applet can not be installed through Widgets Explorer you need to build and install it by yourself as described at README file

**Comment by inquisitiv3** [comment]
Why isn't it possible to install it via the widget explorer?

**Comment by psifidotos** [comment]
Because it has c++ libraries and code that need to be built and installed first

**Comment by agent188** [comment]
After compiling from AUR, I could not find this widget in the same way.

**Comment by misketmuskat** [comment]
I am having similar problem. I built plasma5-applets-window-appmenu from AUR, however I cannot find the applet on widget list.
