### ISSUE TITLE
Different menues appear one by one with a latency in between

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/applet-window-appmenu#6]
I filled this bug against plasma's global menu, but I as far as I can see it applies to this applet too. Ideally all **appmenu's buttons** (forgot adding buttons) should appear in sync.

https://bugs.kde.org/show_bug.cgi?id=398357

Relevant comment:

The latency I refer to, occurs because menues are loaded one after the other. This is fine, but I would recommend to separate the loading (which I assume is slow), from the showing (which I assume can be instantaneous to the human eye). If so, while menues are being imported, the applet should keep them invisible, and once all are loaded, then show them all.

**Comment by psifidotos** [comment]
we 'll see... first I must play with it...

**Comment by psifidotos** [comment]
do you have any video demonstrating the no latency you are describing?

**Comment by kupiqu** [comment]
I'll try to make one when I have a chance (so long since I did one, so I have to refresh my memory). In the meantime, you can move back and forth between kate and konsole and see how same name menues appear in sync (File, Edit, Visualize), while those that are different appear later, creating a "pseudo-artifact" to the human eye: please repeat this several times while focusing on konsole's Bookmarks.

I think if the menu transition would be masked (until ready), all buttons would appear in sync, and this effect would disappear.

**Comment by psifidotos** [comment]
> I think if the menu transition would be masked (until ready), all buttons would appear in sync, and this effect would disappear.

I tried but I dont see anything annoying... I will wait for your demonstration...

**Comment by kupiqu** [comment]
Gif:

![screenrecording-2018-11-17_12](https://user-images.githubusercontent.com/3875196/48664028-9dcfb880-ea66-11e8-837a-893b0901f1b2.gif)

**Comment by psifidotos** [comment]
so what is the issue?

**Comment by kupiqu** [comment]
`Fitxer`, `Edita`, `Visualitza`, they appear in both and the transition is immediate.

If you focus on `Adreces d'Interès` and subsequent, you can a delay in their appearance.

**Comment by psifidotos** [comment]
this is how Repeater element of QML works I dont think you can do something about it or at least I dont have any expertise that could change that behavior.

**Comment by kupiqu** [comment]
> this is how Repeater element of QML works I dont think you can do something about it or at least I dont have any expertise that could change that behavior.

Yes, I know. I was suggesting to go through the repeater but somehow mask the output in the applet until it goes through them all. It would be like running the repeater loop twice, once to update (slow) and a second one to show (fast).

I guess it's easy to say but hard, or even not possible, to implement.
