### ISSUE TITLE
Window Title not appear

### ISSUE THREAD

**Issue by raniaamina** [psifidotos/applet-window-appmenu#60]
Hi
When i running something, there are no window title between button and menus, any ideas to solve this problem?
![gambar](https://user-images.githubusercontent.com/22146607/56876788-f70b3180-6a73-11e9-915d-437e73b64863.png)

Thanks :")

**Comment by psifidotos** [comment]
Show me your settings window

**Comment by psifidotos** [comment]
The problem is for window appmenu or window title?

**Comment by raniaamina** [comment]
![gambar](https://user-images.githubusercontent.com/22146607/56885498-bec91a80-6a96-11e9-9528-598d1ff7c989.png)


Is this what you mean?

**Comment by psifidotos** [comment]
Add the Window Title applet if you want window title in your panel
