### ISSUE TITLE
Feature Request: Refreshing menu

### ISSUE THREAD

**Issue by beojan** [psifidotos/applet-window-appmenu#62]
Some apps display no menu when a global menubar is enabled. Some way to forcibly refresh the menu would help debug / workaround this.

**Comment by psifidotos** [comment]
I don't understand

**Comment by beojan** [comment]
For instance, LibreOffice doesn't display any menus in the global menubar until minimized and maximized.

Now I'm trying to find out why Krita 4.2 isn't displaying any menus. It would help if the window menu applet had some way to manually force the menus to be refreshed.

**Comment by psifidotos** [comment]
If you don't minimize maximize what does it show?

**Comment by psifidotos** [comment]
2. What are your Qt, Plasma and Distro versions?

**Comment by beojan** [comment]
It looks like something (probably Libreoffice) got updated, and this is fixed now. With Krita, no menus are displayed in the global menubar or in the application itself.

Qt 5.12, Plasma 5.15, Distro is Arch.

**Comment by psifidotos** [comment]
Probably an upstream issue of some kind...

Krita global menu works just fine in my Tumbleweed system.

**Comment by beojan** [comment]
I'm sure. Krita 4.1.8 works fine, so it's clearly a regression in Krita. I'm just trying to figure out what's causing it.

**Comment by psifidotos** [comment]
upstream
