### ISSUE TITLE
Add dependency required to install in readme file

### ISSUE THREAD

**Issue by pramitbiswas** [psifidotos/applet-window-appmenu#63]
like `sudo apt install extra-cmake-modules qtdeclarative5-dev libkf5plasma-dev libqt5x11extras5-dev` and other. I'm unable to compile, as unable to find exact package name of the dependencies. Currently stuck at "The X11 Session Management (SM) development package could not be found"

**Comment by psifidotos** [comment]
this is distro specific and I dont add notes per distro... Following the Latte approach I can add an INSTALLATION.md file that will be community maintained....

**Comment by pramitbiswas** [comment]
Thanks. Something is better than nothing.

**Comment by psifidotos** [comment]
done, https://github.com/psifidotos/applet-window-appmenu/blob/master/INSTALLATION.md
