### ISSUE TITLE
Feature request: Double click (and/or drag from) global menu bar to de-maximize window

### ISSUE THREAD

**Issue by 89iuv** [psifidotos/applet-window-appmenu#68]
I use the title bar a lot to manipulate windows. 
Normally i would drag the window to the top to maximize it and i would expect to be able to do the same in reverse.

I do not know if this is possible so the next best thing which would help me a lot is to use a mouse double click on the global menu bar to de-maximize the window.

I have the global menu bar set to span the entire length of the main panel, up until the notifications tray area.

**Comment by psifidotos** [comment]
In what panel have you added the applet in Latte or Plasma?

**Comment by 89iuv** [comment]
In plasma.

**Comment by psifidotos** [comment]
In applet level this is not possible...

Latte panels from Latte git version support this... You can drag/maximize/restore the active window from empty areas of the Latte panel

**Comment by 89iuv** [comment]
So all i need to do is to use a latte panel and it should work. I will try it as soon as i can. Thank you.

**Comment by psifidotos** [comment]
Yes, in Latte git version  you can find these options at Behavior tab in advanced mode..

Take note that in stable Latte v0.8 this is not supported

**Comment by psifidotos** [comment]
https://m.youtube.com/watch?v=d7xl1I8wMxI

in minute 1:10 you can see the mentioned setting in Actions group
