### ISSUE TITLE
sometimes the button can stand out even if the cursor is not on the button

### ISSUE THREAD

**Issue by agent188** [psifidotos/applet-window-appmenu#69]
sometimes the button can stand out even if the cursor is not on the button

**Comment by agent188** [comment]
![image](https://user-images.githubusercontent.com/41228098/58711925-335de480-83c8-11e9-97d5-26f41e942dbd.png)

**Comment by psifidotos** [comment]
1. What if your AppMenu applet version? (it has very long to occur in my system)
2. Are you using Latte or Plasma panels?

**Comment by agent188** [comment]
I use a plasma panel
I am using version with AUR (0.4.2-1)

**Comment by psifidotos** [comment]
Do you have any concrete way to reproduce this?

**Comment by agent188** [comment]
1. Click on the first button in the menu in one application
2. Select the second application window

**Comment by psifidotos** [comment]
What is the second application window?

**Comment by psifidotos** [comment]
I tried with a plasma panel and latest appmenu applet and I can not reproduce.
Is it possible to create a video demonstrating how you reproduce this and upload it in google drive OR dropbox? NOT youtube

**Comment by marhkb** [comment]
I figured out that I always have that issue when the widget is locked as show in the screen. Everything is ok when it is unlocked

![appwindow_locked](https://user-images.githubusercontent.com/3630213/67591844-9e84ca80-f75e-11e9-8d1c-e1b4c90879ac.png)
