### ISSUE TITLE
Buttons size increase when pressing Alt "_"

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/applet-window-appmenu#7]
Please see gif:

![screenrecording-2018-11-17_12 09 47](https://user-images.githubusercontent.com/3875196/48663757-c3f35980-ea62-11e8-8bad-38e00660641f.gif)

**Comment by psifidotos** [comment]
this does not happen in my system... and in plama panel how does it look?

**Comment by psifidotos** [comment]
sorry I mean plasma global menu applet

**Comment by huyndnse63331** [comment]
Hi @psifidotos , i'm having the same problem on Kubuntu 20.04 (amd64), KDE Plasma 5.18.5. I mostly use NetBeans, since the keymap to reformat the code is Alt + Shift + F, but when pressing this combination of keys, the menu bar of Window Menu is triggered, which really annoys. Can you consider checking this problem, if you cannot reproduce this problem, i can attach a video. Thanks

**Comment by trmdi** [comment]
> keymap to reformat the code is Alt + Shift + F

Can't you just change it?

**Comment by huyndnse63331** [comment]
> > keymap to reformat the code is Alt + Shift + F
> 
> Can't you just change it?

There are a lot of keymap using Alt, even in JetBrains's IDEs and others, not just NetBeans though.

**Comment by psifidotos** [comment]
How do you solve this with Plasma Global menu?

**Comment by huyndnse63331** [comment]
I did not, that's why i'm looking for another alternative for Global Menu and i saw yours. :D

**Comment by huyndnse63331** [comment]
I'm just using an alternative solution, but this is not nice at all. Instead of checking "Show full application menu", i check the other one which is "Use single button for application menu" and the menu looks uglier.

![image](https://user-images.githubusercontent.com/25204246/85941700-877e2400-b94e-11ea-88c8-a91ecd4bb182.png)

**Comment by psifidotos** [comment]
https://github.com/psifidotos/applet-window-appmenu/blob/master/package/contents/code/util.js

What happens is that these characters gain an underline html tag. Some how that adds margins, it could be also a font issue... In a text editor normal text and underlined text do they look consistent?

**Comment by huyndnse63331** [comment]
When you hold Alt, those texts will be underline which is waitng for another key is pressed and trigger the specific menu, like Alt + F will trigger File menu. I wonder if there is any way i can press Alt + Shift + F without triggering the menu bar while the menu bar shows everything like this.

![image](https://user-images.githubusercontent.com/25204246/85942013-cdd48280-b950-11ea-8b57-09de311f347d.png)

**Comment by psifidotos** [comment]
> When you hold Alt, those texts will be underline which is waitng for another key is pressed and trigger the specific menu, like Alt + F will trigger File menu. I wonder if there is any way i can press Alt + Shift + F without triggering the menu bar while the menu bar shows everything like this.
> 
> ![image](https://user-images.githubusercontent.com/25204246/85942013-cdd48280-b950-11ea-8b57-09de311f347d.png)

This is another issue, you need to open a new bug report, you want Alt to not trigger menus, for example to choose other modifier for this.

**Comment by huyndnse63331** [comment]
> > When you hold Alt, those texts will be underline which is waitng for another key is pressed and trigger the specific menu, like Alt + F will trigger File menu. I wonder if there is any way i can press Alt + Shift + F without triggering the menu bar while the menu bar shows everything like this.
> > ![image](https://user-images.githubusercontent.com/25204246/85942013-cdd48280-b950-11ea-8b57-09de311f347d.png)
> 
> This is another issue, you need to open a new bug report, you want Alt to not trigger menus, for example to choose other modifier for this.

How can i change the modifier for this widget since i don't want Alt to trigger any menu?

**Comment by psifidotos** [comment]
Add a new feature request in order to be discussed

**Comment by psifidotos** [comment]
looks like a font issue... feel free for anyone to provide different findings
