### ISSUE TITLE
[Feature Request] Make menus and their items color customizable

### ISSUE THREAD

**Issue by Morvs** [psifidotos/applet-window-appmenu#70]
Scenario: You use a top panel with global menu with dark color and a light colored widget theme like Breeze. Now the menu items are light colored. While this is fine for the the context menus inside the applications it's looking somewhat weird for the menus of the global menu.

It would be nice if the menus and their items of the global menu could be color customizable. One color for all menus would be fine for personally. It should not affect any other menu color.

**Comment by psifidotos** [comment]
![image](https://user-images.githubusercontent.com/2216474/67623569-9183dc00-f82f-11e9-8bd9-b5bb739999b9.png)

**Comment by psifidotos** [comment]
![image](https://user-images.githubusercontent.com/2216474/67623582-abbdba00-f82f-11e9-81ce-e42425649676.png)

**Comment by psifidotos** [comment]
How things work...

**Plasma**
Menu Colors: Can be either Default or choose from all available installed color schemes in your system

**Latte>=v0.9.4**
Default, Current Window used for the appmenu, or from any color scheme available in your system....

**Comment by Morvs** [comment]
Awesome 👍 Will try this soon.
