### ISSUE TITLE
[feature] Allow full menu reveal on hover at all times.

### ISSUE THREAD

**Issue by ripefig** [psifidotos/applet-window-appmenu#71]
![image](https://user-images.githubusercontent.com/45201036/59551697-350dd780-8f86-11e9-9e4d-764b77b684b9.png)
![image](https://user-images.githubusercontent.com/45201036/59551698-3b03b880-8f86-11e9-98ce-5d9a296074a3.png)

With the current behavior, the menubar that gets revealed by hovering over the title, gets cut off if there other widgets in the panel take up too much space.

This makes it tricky to use a single-top-panel layout, which is probably the most optimal and simplest layout there is. For example, if you're using multiple screens, side panels are hard to use because the mouse doesn't stop at the edge. Also a single panel takes up less space and is more straightforward to use.

I know this is a hard problem to solve, but it would be nice if the menubar could be superimposed on the on other widgets (mainly the dock).

I think it may be desirable to have a general solution to this problem, by breaking up a single panel into multiple parts and having each part be revealed on hover. So by default, you have the dock segment covering the other segments (2), but when you hover over over other segments, they cover the dock (2,3). So in (2), if you hover over the title/menubar, you have the menubar segment covers the dock segment, whicle in (3) if you hover over the tray segment, the tray segment covers the dock area.

Proposed (general behavior):

![image](https://user-images.githubusercontent.com/45201036/59552098-37266500-8f8b-11e9-8a60-cb947c462219.png)

A less flexible, stopgap solution would be to combine the dock/meneubar/title/buttons, as you have already done with title/menubar.

**Comment by psifidotos** [comment]
no idea how this can be achieved
