### ISSUE TITLE
Show Window Title applet on mouse exit disabled

### ISSUE THREAD

**Issue by Elanzer47** [psifidotos/applet-window-appmenu#74]
![appmenu](https://user-images.githubusercontent.com/8043810/62097426-268d2e00-b25d-11e9-88a6-21dcd679b6f6.png)

I updated today to latte-dock 0.9 and updated all applets to 0.5 (Installed from kde.store).

I tried to use this new feature, but it's disabled and i dont know why

I'm on Manjaro Testing

**Comment by psifidotos** [comment]
Is not finding Window AppMenu.

Window AppMenu needs to be build and installed, it can not be installed through Widgets explorer

**Comment by psifidotos** [comment]
Sorry I mean it does not find Window Title Applet >= 0.5 maybe you need to restart your system as long as you are using Latte 0.9, Window Title applet >= 0.5 and Window AppMenu>=0.5

**Comment by Elanzer47** [comment]
I installed Window Title from source and now it's working. I tried installing directly from widget explorer and it wasn't updating the applet.
