### ISSUE TITLE
Font alignment with title-applet it's a little off

### ISSUE THREAD

**Issue by Elanzer47** [psifidotos/applet-window-appmenu#75]
![fonte](https://user-images.githubusercontent.com/8043810/62097682-0611a380-b25e-11e9-85a2-a2ccdada73f5.png)

Another I faced today updating to latte 0.9 and applets to 0.5.

Font alignment was perfect before update. I know it's very small problem but really bothers me (I'm little crazy about simmetry), and I tried but was unable to align messing with the panel.

**Comment by psifidotos** [comment]
Latte v0.9 is designed to provide you with perfect symmetry, so all the symmetry issue falls to applets. What is the applet left to AppMenu?

**Comment by psifidotos** [comment]
Checked with my system and I see it also. I WONT add any workaround for this, any workaround fixes it for half of the users and for the rest appears. So I am also in the  HALF that is hit by it, and that helped me move to Unity behavior for Window Title and AppMenu.

Now, if anyone manage to find a real FIX/SOLUTION for this then no problem but I can NOT.  There is a big chance that this is reaching Qt side

**Comment by psifidotos** [comment]
@Elanzer47 the moment I was disappointed, the same moment I found I think the issue... Please if you can build from master test the with last commit to confirm that this is fixed

**Comment by Elanzer47** [comment]
It's working now, very pleaseant to see. Thanks
