### ISSUE TITLE
Akregator: AppMenu not showing for App if autostarted

### ISSUE THREAD

**Issue by keiichiiownsu12** [psifidotos/applet-window-appmenu#76]
Hello! 

This is just a minor bug. I autostart akregator (i.e. ~/.config/autostart/.org.kde.akregator.desktop), with the --no-mainwindow argument (i.e. so it starts minimized in system tray).

For whatever reason, when I open an akregator window (e.g. by clicking on its system tray icon), the AppMenu widget does not show. However, if I were to kill akregator (i.e. by right-clicking system tray and selecting "Quit", thus killing the program. Or simply pkill akrogrator) and restart it, the AppMenu shows just fine.

Interesting issue? Have not confirmed it with other autostarting apps. Can test another (e.g. discord) and let you know if the same issue happens!

**Comment by keiichiiownsu12** [comment]
Tested this using discord, firefox, and kate configured as autostarting.

AppMenu would show for auostarted discord and firefox, but not for Kate

**Comment by psifidotos** [comment]
The AppMenu is in Latte or panel?

**Comment by keiichiiownsu12** [comment]
Apologies. AppMenu is in latte-dock (as a panel)

**Comment by psifidotos** [comment]
That would mean that Latte loads and registers its service after these apps have been opened through autostart. This could be solved if you delay the autostart for this apps OR if Latte finds a way to start much earlier but I have no idea if this is possible

**Comment by keiichiiownsu12** [comment]
Curious, because if I autostarted non KDE apps, e.g. firefox and discord, the menu bar shows.

Hmm, I'll try and see if I can do as you suggest (can call apps from ~/.profile instead of putting them in ~/.config/autostart as one option), then report back
