### ISSUE TITLE
Menu hover effect "stuck"

### ISSUE THREAD

**Issue by ripefig** [psifidotos/applet-window-appmenu#77]
![image](https://user-images.githubusercontent.com/45201036/63854174-3bb4c400-c9a5-11e9-96ea-02592cc206d6.png)

This happens pretty often, but not consistently. As you can see the menu isn't open and there is no mouse hovering over it but it's there is still a highlight box.

This may be related to a more serious bug where the menu gets stuck in shown state with the "Show Window Applet on mouse enter"/"Hide on mouse exit" option. In other words the menu won't hide on mouse exit.

In both cases you have to hover over the menu area a second time to get rid of the glitch.

**Comment by psifidotos** [comment]
1. Latte or Plasma?
2. how can I reproduce?
3. pretty hard to solve based on the implementation used, but who knows...

**Comment by psifidotos** [comment]
duplicate #69
