### ISSUE TITLE
Will this be added to the default repository for Plasma Widgets?

### ISSUE THREAD

**Issue by mcolinp** [psifidotos/applet-window-appmenu#78]
This looks to be exactly what I am looking for to replace Global Menu or Active Window Control, in Manjaro KDE. Global Menu lacks features; and the text is not configurable. Active Window Control crashes Plasma on me constantly. 

I am hoping there will be simpler way to get this installed using the normal widgets 'Download New Widgets' option. While I can go through detailed instructions to try and install; I find that once things need updating, or dependencies change or need updating . . . I get lost. 

Surely there are many others who would also like a simple 'Add Widget" option without jumping through hoops. 

Don't take this as being critical of the Widget itself; it looks to be very well done.

**Comment by psifidotos** [comment]
No I don't think so
