### ISSUE TITLE
"show only menus from active applications" fails when krunner or an application launcher is active

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/applet-window-appmenu#8]
Just what the title say: the option "show only menus from active applications" fails when krunner or an application launcher is active.

**Comment by psifidotos** [comment]
yeah makes sense... currently only plasma desktop is supported...

for all the other windows there must be check if they belong the currentWindow e.g. in case you open the Save dialog of LibreOffice then the menu should not become hidden...

**Comment by kupiqu** [comment]
Works perfect now :)
