### ISSUE TITLE
Display useless menu without sub

### ISSUE THREAD

**Issue by SettingDust** [psifidotos/applet-window-appmenu#81]
When I active a window without menu.
The widget show "File Edit Help" menu. But it has no sub menu and function.
So I think item should be removed when it without subs

**Comment by psifidotos** [comment]
1. What applet version?
2. Latte OR Plasma panel?
3. show me  a screenshot of the situation

**Comment by psifidotos** [comment]
you need to find me a way to reproduce this because in my system this does not happen

**Comment by SettingDust** [comment]
> 1. What applet version?
> 2. Latte OR Plasma panel?
> 3. show me  a screenshot of the situation

1. 0.5.1
2. Latte
3. When I open the Applet Window Appmenu settings, it done.
 ![](https://i.imgur.com/MdKfZm8.jpg)

**Comment by psifidotos** [comment]
This is intentional, when you open the AppMenu settings window you should get a visual feedback

**Comment by SettingDust** [comment]
> This is intentional, when you open the AppMenu settings window you should get a visual feedback

And telegram is intentional too?

**Comment by SettingDust** [comment]
And there is another bug appear randomly.

!()[https://i.imgur.com/BDRjpwa.jpg]
!()[https://i.imgur.com/zEI5em3.jpg]

**Comment by psifidotos** [comment]
> And telegram is intentional too? In my screenshot, the active window is telegram.

Yes, because you have opened the AppMenu settings then you should get visual feedback when no other appmenu is provided

> It doesnt have menu but the chrome's menu is been shown

no idea what you are describing, please open a new bug report for this with full explanation/way to reproduce
