### ISSUE TITLE
Randomly bug

### ISSUE THREAD

**Issue by SettingDust** [psifidotos/applet-window-appmenu#82]
A Bug is appearing randomly.
It doesnt have menu but the others' menu is been shown

![](https://i.imgur.com/BDRjpwa.jpg)
![](https://i.imgur.com/zEI5em3.jpg)

**Comment by psifidotos** [comment]
how do you reproduce this?

**Comment by psifidotos** [comment]
what is your Latte version?

**Comment by SettingDust** [comment]
> what is your Latte version?

0.9.1

**Comment by SettingDust** [comment]
> how do you reproduce this?

Switch the window. Randomly.

**Comment by psifidotos** [comment]
Send me your latte layout file to test it out

**Comment by SettingDust** [comment]
> Send me your latte layout file to test it out

Sry for that I have changed it. Can a screenshot help you?

**Comment by psifidotos** [comment]
Nope a screenshot wouldn't help, you can find your Latte layout file at, ~/.config/latte folder

Can you try also that this is still valid with Latte 0.9.2?

**Comment by SettingDust** [comment]
> Nope a screenshot wouldn't help, you can find your Latte layout file at, ~/.config/latte folder
> 
> Can you try also that this is still valid with Latte 0.9.2?

OK, I do

**Comment by SettingDust** [comment]
It isnt latte's problem. The kwin panel reproduce too. 
I have opened a chrome and right-click on Window Title to open a Setting. 
And it done. But just one time. Can't reproduce. Im trying

**Comment by psifidotos** [comment]
ok, if you manage to find a way to reproduce please report back

**Comment by psifidotos** [comment]
so way to reproduce this... closing...
