### ISSUE TITLE
Appmenu lingers after mouse exit with: Show Window Title  applet on mouse exit &  Fill available space in Window Title

### ISSUE THREAD

**Issue by ChrisP4** [psifidotos/applet-window-appmenu#83]
1. set window appmenu to show window title applet on mouse exit
2. set the window title applet to fill all available space
3. move cursor in blank space/ the appmenu appears
4. remove the cursor from the blank space → the appmenu doesn't disappear

(I'm not sure if this is the correct place for the issue)

Thanks! :)

**Comment by psifidotos** [comment]
have you enabled in Window AppMenu: "Always Use Maximum Available Width" ?

**Comment by ChrisP4** [comment]
No, I hadn't. I hadn't enabled the fill all available space until recently either, because I thought it wouldn0t let me drag the windows from the panel, but as it turns out, everything works!

Thanks a lot, that was super fast.

**Comment by psifidotos** [comment]
;)
