### ISSUE TITLE
Show placeholder text while in the 'widget moving' mode of the panel

### ISSUE THREAD

**Issue by Kishore96in** [psifidotos/applet-window-appmenu#84]
If we unlock widgets and click on the panel settings (the little button that opens the bar with 'lock widgets', 'remove panel', 'add widgets' etc.) the applet becomes blank since there is currently no menu to display, and one has to guess at its current position in order to move the applet. Ideally, it would show some placeholder text in the moving mode so that the user can locate the applet on the panel.

Screenshot: https://i.imgur.com/8ue8RaX.png
Version: 0.5.1
I am using this with a Plasma panel, and not with Latte dock.

**Comment by psifidotos** [comment]
makes sense, but unfortunately this is upstream....
Plasma panels do not inform their applets when they are in that state. Latte on the other hand it does if the applets are using the Latte Communicator way https://techbase.kde.org/LatteDock#Can_a_Plasma_Applet_access_Latte_Information.3F

**Comment by Sadi58** [comment]
@Kishore96in 
If you use Latte Dock as a Panel (as well as a Dock), you won't have such a problem.
It shows all of the widgets added to the panel, it doesn't matter if they'de visible or invisible, so you can easily position them.
