### ISSUE TITLE
Extra packages needed for OpenSuse 

### ISSUE THREAD

**Issue by g7fernandes** [psifidotos/applet-window-appmenu#86]
In order to compile, beyond the packages listed at INSTALLATION.md, OpenSuse (at least Leap) users must also install  **libkdecoration2-devel kconfigwidgets-devel kwidgetsaddons-devel kdeclarative-devel** .
Users who also want to compile the applet-window-buttons must also have **ki18n-devel**.

**Comment by psifidotos** [comment]
the INSTALLATION.md files are community driven... I will be waiting for your PRs
