### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by madjoe** [psifidotos/applet-window-appmenu#89]
I just tried to install this from GUI element "Add widget" in my Manjaro KDE that meets the requirements/dependencies of the widget. However, I am facing the following issue during installation:

`plasmashell	org.kde.knewstuff.core: Command ' "kpackagetool5 --install /tmp/applet-window-appmenu-0.6.0.tar.gz --type Plasma/Applet" ' failed with code 4
`

Any idea what's going on here?

**Comment by psifidotos** [comment]
You can not install it that way. Either you need to build it yourself like the end of README file describes Or you need to rely on your distro to provide it for you.
