### ISSUE TITLE
app menu leaves a blank space if the active app doesn't have any menus (like gtk apps)

### ISSUE THREAD

**Issue by himsin** [psifidotos/applet-window-appmenu#9]
Screenshot --> https://imgur.com/a/nzFV3xB
Please see top left corner where there is an empty space with mouse tooltip

**Comment by psifidotos** [comment]
@himsin please test again with latest master and provide feedback what is happening, is it fixed? not?

what application produces this for you?

**Comment by himsin** [comment]
perfect! working fine now. I noticed this with pamac. 
Thanks for the quick fix and great support :1st_place_medal:

**Comment by psifidotos** [comment]
I introduced https://github.com/psifidotos/applet-window-appmenu/issues/10 and during adding that feature I fall also at your problem... ;)
