### ISSUE TITLE
Error "unknown type `a(ia{sv})'" when compiling

### ISSUE THREAD

**Issue by Slater91** [psifidotos/applet-window-appmenu#91]
Hi.
Thank you for your work on this widget and on Latte. I tried installing this widget but I could not compile it. I installed all required dependencies, but when I compile the code it returns this error:
`Got unknown type 'a(ia{sv})'
You should add <annotation name="org.qtproject.QtDBus.QtTypeName.In0" value="<type>"/> to the XML description
plugin/libdbusmenuqt/CMakeFiles/dbusmenuqt.dir/build.make:65: recipe for target 'plugin/libdbusmenuqt/dbusmenu_interface.cpp' failed
make[2]: *** [plugin/libdbusmenuqt/dbusmenu_interface.cpp] Error 1
CMakeFiles/Makefile2:688: recipe for target 'plugin/libdbusmenuqt/CMakeFiles/dbusmenuqt.dir/all' failed
make[1]: *** [plugin/libdbusmenuqt/CMakeFiles/dbusmenuqt.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2`
I am using KDE neon with all latest updates applied. Please let me know if you need any additional info.

**Comment by psifidotos** [comment]
Compiles just fine in my system

**Comment by Slater91** [comment]
Yeah, well, thank you very much for your help, I will surely tell other people how helpful you've been!

**Comment by psifidotos** [comment]
> Yeah, well, thank you very much for your help, I will surely tell other people how helpful you've been!

thank u! Please do so!!!

**Comment by Slater91** [comment]
Michail, I really appreciate your work. I love Latte Dock. Thank you so much for all the effort you put in this project - I am sincerely grateful for your work.
But also, please understand that telling me "it works on my machine" is incredibly irritating and frustrating. I understand you can't possibly respond to every single request for help, but providing me with at least some indication of what might not work would help both in solving the issue and in not making me feel frustrated. This is not how issues should be dealt with, especially since I raised a real issue - I'm used to compile software from source, so when I say I followed all the instructions and it doesn't work, it means there is probably something missing in the documentation. Please consider that.

**Comment by psifidotos** [comment]
The error you get is from: https://github.com/psifidotos/applet-window-appmenu/blob/master/plugin/libdbusmenuqt/com.canonical.dbusmenu.xml

from my understanding if you have installed Qt and its DBus modules you should be fine for anything more I have no idea, you could ask Neon community about it... that part of the code is also part of the Plasma original Global Menu so it is just a matter of missing requirements...

If you manage to find what is missing you can update afterwards the INSTALLATION.md file. For ALL my projects the INSTALLATION.md files are COMMUNITY/DISTRO RESPONSIBILITY to update and maintain...

**Comment by Slater91** [comment]
Thank you, this helps. I will let you know whether I find anything meaningful.
