### ISSUE TITLE
Merge Window AppMenu and Window Title into one Applet

### ISSUE THREAD

**Issue by EllBock** [psifidotos/applet-window-appmenu#96]
Hi, I'm using your applets to mimick macOS's top bar in KDE. 
I'm struggling to make the two applets work together consistently. There are some occasions in which they show different information.
For example, with pop-up menus (like confirmation dialogs, or file properties in Dolphin) 
* while using Plasma panels, when some pop-up appears the title won't display anything, while the appmenu shows some menu (I suppose the dialog's parent).
* while using Latte docks, pop-ups' names are shown, even the name "Latte" is shown if you open an applet from the docks, but the menu stays unchanged from the previous one. Thus, if you open a Latte applet, the name would be "Latte" but there would be a menu which does not refer to the Latte "app". The first problem is addressed, but this other one appears.

There are also some strange behaviours with Latte docks. In multi-monitor setups with multiple latte docks per screen, when opening an app from the docks all Title applets change their name, even if the "Show only information from current screen" option is ticked. This might be happening because the latte docks retain the information in some way (if you focus a window on another screen, the menu and the title do not disappear), but when you update one of the titles, the other ones seem to change with it. Also, when changing virtual desktops, the only applets updating are the ones on the "main screen", while the others still show information of windows in the previous desktop. 

Because of these strange behaviours I'm currently using plasma panels, but in general I would like to see the menus of the main app on a screen, even if I'm working on another screen. Right now, with "Show only information from current screen" options ticked on both AppMenu and Title applets, these would disappear if I focus a window on another screen.

What I'm proposing here is to merge the two applets into one, that is, the AppMenu would be able to show the name of the application it's referring to. There's why:
* Given some (sophisticated) options of the AppMenu applet, inconsistencies between shown name and shown menu would not occur.
* The graphical behaviour of the whole applet would be more consistent than having the two separated. Think about changing focused window, the two applets do not respond at the same time, and strange animations appear because of the resizing of the Title applet.
* A possible feature would be making the title clickable, showing the same menu that KDE shows when right-clicking on the titlebar of a window.
* I believe the "bugs" I'm referring to might be easier to squash if you work on a single applet.

You could still ship both applets separately, because someone might just want the title without the menu, but I believe that there would be a lot of people wanting to activate a "Show window title" option in the AppMenu applet.

Thanks for your great work. I hope my english was clear enough. If you need anything else, just ask.

**Comment by psifidotos** [comment]
Sorry I am not interested in merging. If you think the applets behave faulty, you can always open issues for reporting your findings and test if the faults are bugs or intentional behavior.
